### ISSUE TITLE
IKEA SYMFONISK

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-zp#101]
Got myself an IKEA SYMFONISK Bookshelf for less than € 100,-.  As advertised, it works like any other zone player, also with homebridge-zp.

The Sonos app recognises it as an `IKEA SYMFONISK Bookshelf` (in the _About My Sonos_ window), but the device description only mentions `Sonos SYMFONISK`, and, of course, the model ID, `S21`.  Although atypical, I think they might have mapped the model ID to the text in the app.

I would appreciate if some-one with a SYMFONISK lamp could check what the Sonos app reports in the _About_ window, and post the output of `zp -H xx.xx.xx.xx description`.

According to the description, it has double the memory of my latest model Play:1.  That could explain why the Play:1 doesn't support AirPlay (even though is does advertise the `MediaRenderer/VirtualLineIn` service).

**Comment by daenjiel** [comment]
Hi, first I want to thank you for your work!

Here are my reports from the Sonos App and homebridge-zb. Model ID of the Table Lamp is `S20`

Sonos App:
`IKEA SYMFONISK Table Lamp: Bedroom
Serial Number: XX-XX-XX-XX-XX-XX:X
Version: 10.3 (build 51166240)
Hardware Version: 1.20.2.3-2
Series ID: A100
IP Address: 192.168.0.94
WM: 1`

homebridge-zb:
`{
  "specVersion": {
    "major": 1,
    "minor": 0
  },
  "device": {
    "deviceType": "urn:schemas-upnp-org:device:ZonePlayer:1",
    "friendlyName": "192.168.0.94 - Sonos SYMFONISK",
    "manufacturer": "Sonos, Inc.",
    "manufacturerUrl": "http://www.sonos.com",
    "modelNumber": "S20",
    "modelDescription": "Sonos SYMFONISK",
    "modelName": "Sonos SYMFONISK",
    "modelUrl": "http://www.sonos.com/products/zoneplayers/S20",
    "softwareVersion": "51.1-66240",
    "swGen": 1,
    "hardwareVersion": "1.20.2.3-2",
    "serialNum": "XX-XX-XX-XX-XX-XX:X",
    "macAddress": "XX:XX:XX:XX:XX:XX",
    "udn": "uuid:RINCON_XXXXXXXXXXXXXXXXX",
    "iconList": [
      {
        "id": 0,
        "mimetype": "image/png",
        "width": 48,
        "height": 48,
        "depth": 24,
        "url": "/img/icon-S20.png"
      }
    ],
    "minCompatibleVersion": "50.0-00000",
    "legacyCompatibleVersion": "36.0-00000",
    "apiVersion": "1.13.2",
    "minApiVersion": "1.1.0",
    "displayVersion": "10.3",
    "extraVersion": "",
    "roomName": "Bedroom",
    "displayName": "SYMFONISK",
    "zoneType": 22,
    "feature1": "0x00000000",
    "feature2": "0x00403332",
    "feature3": "0x0001010e",
    "seriesid": "A100",
    "variant": 0,
    "internalSpeakerSize": 5,
    "bassExtension": "75.000",
    "satGainOffset": "6.000",
    "memory": 512,
    "flash": 256,
    "ampOnTime": 10,
    "retailMode": 0,
    "serviceList": [
      {
        "serviceType": "urn:schemas-upnp-org:service:AlarmClock:1",
        "serviceId": "urn:upnp-org:serviceId:AlarmClock",
        "controlUrl": "/AlarmClock/Control",
        "eventSubUrl": "/AlarmClock/Event",
        "scpdUrl": "/xml/AlarmClock1.xml"
      },
      {
        "serviceType": "urn:schemas-upnp-org:service:MusicServices:1",
        "serviceId": "urn:upnp-org:serviceId:MusicServices",
        "controlUrl": "/MusicServices/Control",
        "eventSubUrl": "/MusicServices/Event",
        "scpdUrl": "/xml/MusicServices1.xml"
      },
      {
        "serviceType": "urn:schemas-upnp-org:service:DeviceProperties:1",
        "serviceId": "urn:upnp-org:serviceId:DeviceProperties",
        "controlUrl": "/DeviceProperties/Control",
        "eventSubUrl": "/DeviceProperties/Event",
        "scpdUrl": "/xml/DeviceProperties1.xml"
      },
      {
        "serviceType": "urn:schemas-upnp-org:service:SystemProperties:1",
        "serviceId": "urn:upnp-org:serviceId:SystemProperties",
        "controlUrl": "/SystemProperties/Control",
        "eventSubUrl": "/SystemProperties/Event",
        "scpdUrl": "/xml/SystemProperties1.xml"
      },
      {
        "serviceType": "urn:schemas-upnp-org:service:ZoneGroupTopology:1",
        "serviceId": "urn:upnp-org:serviceId:ZoneGroupTopology",
        "controlUrl": "/ZoneGroupTopology/Control",
        "eventSubUrl": "/ZoneGroupTopology/Event",
        "scpdUrl": "/xml/ZoneGroupTopology1.xml"
      },
      {
        "serviceType": "urn:schemas-upnp-org:service:GroupManagement:1",
        "serviceId": "urn:upnp-org:serviceId:GroupManagement",
        "controlUrl": "/GroupManagement/Control",
        "eventSubUrl": "/GroupManagement/Event",
        "scpdUrl": "/xml/GroupManagement1.xml"
      },
      {
        "serviceType": "urn:schemas-tencent-com:service:QPlay:1",
        "serviceId": "urn:tencent-com:serviceId:QPlay",
        "controlUrl": "/QPlay/Control",
        "eventSubUrl": "/QPlay/Event",
        "scpdUrl": "/xml/QPlay1.xml"
      }
    ],
    "deviceList": [
      {
        "deviceType": "urn:schemas-upnp-org:device:MediaServer:1",
        "friendlyName": "192.168.0.94 - Sonos SYMFONISK Media Server",
        "manufacturer": "Sonos, Inc.",
        "manufacturerUrl": "http://www.sonos.com",
        "modelNumber": "S20",
        "modelDescription": "Sonos SYMFONISK Media Server",
        "modelName": "Sonos SYMFONISK",
        "modelUrl": "http://www.sonos.com/products/zoneplayers/S20",
        "udn": "uuid:RINCON_XXXXXXXXXXXXXXXXX_MS",
        "serviceList": [
          {
            "serviceType": "urn:schemas-upnp-org:service:ContentDirectory:1",
            "serviceId": "urn:upnp-org:serviceId:ContentDirectory",
            "controlUrl": "/MediaServer/ContentDirectory/Control",
            "eventSubUrl": "/MediaServer/ContentDirectory/Event",
            "scpdUrl": "/xml/ContentDirectory1.xml"
          },
          {
            "serviceType": "urn:schemas-upnp-org:service:ConnectionManager:1",
            "serviceId": "urn:upnp-org:serviceId:ConnectionManager",
            "controlUrl": "/MediaServer/ConnectionManager/Control",
            "eventSubUrl": "/MediaServer/ConnectionManager/Event",
            "scpdUrl": "/xml/ConnectionManager1.xml"
          }
        ]
      },
      {
        "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
        "friendlyName": "Bedroom - Sonos SYMFONISK Media Renderer",
        "manufacturer": "Sonos, Inc.",
        "manufacturerUrl": "http://www.sonos.com",
        "modelNumber": "S20",
        "modelDescription": "Sonos SYMFONISK Media Renderer",
        "modelName": "Sonos SYMFONISK",
        "modelUrl": "http://www.sonos.com/products/zoneplayers/S20",
        "udn": "uuid:RINCON_XXXXXXXXXXXXXXXXX_MR",
        "serviceList": [
          {
            "serviceType": "urn:schemas-upnp-org:service:RenderingControl:1",
            "serviceId": "urn:upnp-org:serviceId:RenderingControl",
            "controlUrl": "/MediaRenderer/RenderingControl/Control",
            "eventSubUrl": "/MediaRenderer/RenderingControl/Event",
            "scpdUrl": "/xml/RenderingControl1.xml"
          },
          {
            "serviceType": "urn:schemas-upnp-org:service:ConnectionManager:1",
            "serviceId": "urn:upnp-org:serviceId:ConnectionManager",
            "controlUrl": "/MediaRenderer/ConnectionManager/Control",
            "eventSubUrl": "/MediaRenderer/ConnectionManager/Event",
            "scpdUrl": "/xml/ConnectionManager1.xml"
          },
          {
            "serviceType": "urn:schemas-upnp-org:service:AVTransport:1",
            "serviceId": "urn:upnp-org:serviceId:AVTransport",
            "controlUrl": "/MediaRenderer/AVTransport/Control",
            "eventSubUrl": "/MediaRenderer/AVTransport/Event",
            "scpdUrl": "/xml/AVTransport1.xml"
          },
          {
            "serviceType": "urn:schemas-sonos-com:service:Queue:1",
            "serviceId": "urn:sonos-com:serviceId:Queue",
            "controlUrl": "/MediaRenderer/Queue/Control",
            "eventSubUrl": "/MediaRenderer/Queue/Event",
            "scpdUrl": "/xml/Queue1.xml"
          },
          {
            "serviceType": "urn:schemas-upnp-org:service:GroupRenderingControl:1",
            "serviceId": "urn:upnp-org:serviceId:GroupRenderingControl",
            "controlUrl": "/MediaRenderer/GroupRenderingControl/Control",
            "eventSubUrl": "/MediaRenderer/GroupRenderingControl/Event",
            "scpdUrl": "/xml/GroupRenderingControl1.xml"
          },
          {
            "serviceType": "urn:schemas-upnp-org:service:VirtualLineIn:1",
            "serviceId": "urn:upnp-org:serviceId:VirtualLineIn",
            "controlUrl": "/MediaRenderer/VirtualLineIn/Control",
            "eventSubUrl": "/MediaRenderer/VirtualLineIn/Event",
            "scpdUrl": "/xml/VirtualLineIn1.xml"
          }
        ],
        "x_Rhapsody-Extension": {
          "deviceId": "urn:rhapsody-real-com:device-id-1-0:sonos_1:RINCON_XXXXXXXXXXXXXXXXX",
          "deviceCapabilities": {
            "interactionPattern": {
              "type": "real-rhapsody-upnp-1-0"
            }
          }
        },
        "x_QPlay_SoftwareCapability": {
          "_": "QPlay:2"
        },
        "iconList": [
          {
            "mimetype": "image/png",
            "width": 48,
            "height": 48,
            "depth": 24,
            "url": "/img/icon-S20.png"
          }
        ]
      }
    ]
  }
}`
