### ISSUE TITLE
Renaming device in HomeKit renames original device as well

### ISSUE THREAD

**Issue by flobernd** [ebaauw/homebridge-zp#106]
Hi there,

I noticed that renaming a Sonos device in HomeKit does rename the original device in the Sonos app as well.

In the Sonos app you have to append/prepend the room name to the device name in order to easily identify the boxes.

As HomeKit  on the other hand is aware of the actual rooms, I usually like to not include the room name in the device name.

With the current synchronization feature of the plugin it's not possible to keep my naming scheme. Would you mind providing an option for it?

Best regards

**Comment by ebaauw** [comment]
> With the current synchronization feature of the plugin

Homebridge-zp doesn’t sync names.  I think you’re changing the name of the AirPlay2 speaker exposed natively?

**Comment by flobernd** [comment]
Oh snap, I should have double checked and looked for a renaming feature in code. You are correct .. I always renamed the Homebridge device and the AirPlay speaker at the same time.
