### ISSUE TITLE
Heartbeat missing, speakers not found. 

### ISSUE THREAD

**Issue by AlfaJackal** [ebaauw/homebridge-zp#107]
Installed your plugin, added it but am not able to find the speakers. 

Config:
```
{
            "name": "Sonos",
            "brightness": true,
            "service": "switch",
            "speakers": true,
            "searchTimeout": 10,
            "platform": "ZP"
        }
```

Here is the output from the log:
```
p 29 13:07:03 Eggman homebridge[31238]: [2019-9-29 1:07:03 PM] Homebridge is running on port 51826.
Sep 29 13:07:03 Eggman homebridge[31238]: [2019-9-29 1:07:03 PM] [Sonos] warning: heartbeat 2, drift 452
Sep 29 13:07:05 Eggman homebridge[31238]: [2019-9-29 1:07:05 PM] [Sonos] warning: heartbeat 4, drift 590
Sep 29 13:07:06 Eggman homebridge[31238]: [2019-9-29 1:07:06 PM] [Sonos] warning: heartbeat 5, drift 425
Sep 29 13:07:08 Eggman homebridge[31238]: [2019-9-29 1:07:08 PM] [Sonos] warning: heartbeat 7, drift 301
Sep 29 13:07:15 Eggman homebridge[31238]: [2019-9-29 1:07:15 PM] [Config] Homebridge Config UI X v4.6.1 is listening on :: port 8081
Sep 29 13:07:30 Eggman homebridge[31238]: [2019-9-29 1:07:30 PM] [Sonos] error: TypeError: Cannot read property 'zonePlayers' of undefined
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform.heartbeat (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:133:48)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform.emit (events.js:198:13)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform.emit (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Delegate.js:148:13)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform._heartbeat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:295:10)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform._beat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:281:18)
Sep 29 13:07:30 Eggman homebridge[31238]:     at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:269:12)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ontimeout (timers.js:436:11)
Sep 29 13:07:30 Eggman homebridge[31238]:     at tryOnTimeout (timers.js:300:5)
Sep 29 13:07:30 Eggman homebridge[31238]:     at listOnTimeout (timers.js:263:5)
Sep 29 13:07:30 Eggman homebridge[31238]:     at Timer.processTimers (timers.js:223:10)
Sep 29 13:07:30 Eggman homebridge[31238]: [2019-9-29 1:07:30 PM] [Sonos] error: TypeError: Cannot read property 'zonePlayers' of undefined
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform.heartbeat (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:133:48)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform.emit (events.js:198:13)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform.emit (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Delegate.js:148:13)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform._heartbeat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:295:10)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ZpPlatform._beat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:281:18)
Sep 29 13:07:30 Eggman homebridge[31238]:     at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:269:12)
Sep 29 13:07:30 Eggman homebridge[31238]:     at ontimeout (timers.js:436:11)
Sep 29 13:07:30 Eggman homebridge[31238]:     at tryOnTimeout (timers.js:300:5)
Sep 29 13:07:30 Eggman homebridge[31238]:     at listOnTimeout (timers.js:263:5)
Sep 29 13:07:30 Eggman homebridge[31238]:     at Timer.processTimers (timers.js:223:10)
```

**Comment by ebaauw** [comment]
How did you install homebridge?  Sonos uses UPnP for device discovery; homebridge-zp needs to run on the same subnet as the zone players.  Make sure to forward multicast traffic if you run homebridge in a container or behind a firewall.

**Comment by AlfaJackal** [comment]
Sonos runs indeed on a different subnet. Multicast reflector, igmp and upnp are activated and/or forwarded from my IoT subnet to private subnet. Sonos could be easily accessed via the Sonos controller. 

I think there is a missing thing in my Unifi network Even though mDNS reflector is correctly installed. 

Only thing I could try is also forwarding 239.255.255.250.

**Comment by ebaauw** [comment]
> Sonos runs indeed on a different subnet.

Generally speaking, that's a bad idea.  Afaik, 239.255.255.250 is a local subnet multicast address, which won't be routed to other subnets.  It uses UDP port 1900.

> Sonos could be easily accessed via the Sonos controller.

Do you run the Sonos controller on the same host as homebridge?

Next to UPnP for discovery, each zone player hosts a SOAP/HTTP server at TCP port 1400.  homebridge-zp hosts a web server to receive Sonos notifications, just as the Sonos controller.  You can set the host/port in config.json.  Double-check that this server is reachable from the subnet where the zone players reside.  See https://github.com/ebaauw/homebridge-zp#troubleshooting.

**Comment by AlfaJackal** [comment]
Thanks for your help. Sonos controller and homebridge are on the same subnet. UDP 1900 is already routed, removed the multicast address though.

I followed you advise to reach the webserver. My homebridge runs on 10.10.0.11, so I changed the port to 2222, because 1400 didn't work - neither does 2222.
One of my Sonos player is for example on 10.20.0.6 and I can reach it under http://10.20.0.6:1400/status. Status under http://10.20.0.6:1400/status opens an empty web page but no error page.

Homebridge-zp is currently the only plugin. Homebridge and the client I try to connect to 10.10.0.11:1400/notify are on the same subnet. I also opened this port between those two subnets.

This is my new config, tested with and without Timeout:
```
        {
            "name": "Sonos",
            "host": "10.10.0.11",
            "port": 1400,
            "service": "switch",
            "speakers": true,
            "platform": "ZP",
            "searchTimeout": 10
        }
```

**Comment by ebaauw** [comment]
> Status under http://10.20.0.6:1400/status opens an empty web page but no error page.

That's not good.  It should show an _Options_ page where you can get some zone player info.

> Homebridge-zp is currently the only plugin.

To rule out homebridge, you might use the `zp` and `upnp` command-line tools included in homebridge-zp.  In particular:
- `upnp -z` to see the zoneplayer responses to an UPnP search;
- `zp -H  10.20.0.6 info` to retrieve the zone player details; and
- `zp -H 10.20.0.6 eventlog` to log the notifications sent by the zone player.

Make sure these commands run from the 10.10 subnet, where homebridge runs.

The http://10.10.0.11:1400/notify troubleshoot page by homebridge-zp should be reachable from the 10.20 subnet, where the zone players reside.

**Comment by AlfaJackal** [comment]
Sorry, there was a typo: 10.20.0.6:1400/status
correctly shows the webpage but not 10.20.0.6:1400/notify

`zp -H 10.20.0.6 Info` brings up this:

```
{
  "address": "10.20.0.6",
  "baseUrl": "http://10.20.0.6:1400",
  "bootSeq": 21,
  "id": "RINCON_949F3E63CB2E01400",
  "lastSeen": 0,
  "modelName": "Sonos Playbar",
  "modelNumber": "S9",
  "name": "Wohnzimmer",
  "role": "master",
  "tvIn": true,
  "version": "10.4",
  "zone": "RINCON_949F3E63CB2E01400",
  "zoneDisplayName": "Wohnzimmer",
  "zoneName": "Wohnzimmer"
}
```

`zp -H 10.20.0.6 eventlog` this: 
`error: cannot determine my IPv4 address`

And `upnp -z` this:
`pnp: searching on 0.0.0.0:43400
upnp: search done`

And http://10.10.0.11:1400/notify doesn’t even opens a webpage if I try to open it from the same subnet.

**Comment by ebaauw** [comment]
> Sorry, there was a typo: 10.20.0.6:1400/status
correctly shows the webpage but not 10.20.0.6:1400/notify

That’s to be expected; the zone players don’t expose a notify endpoint.

> zp -H 10.20.0.6 Info brings up this:

So the 10.10 subnet can reach the zone players on 10.20.

> And upnp -z this:

Not good.  Is the UPnP search request forwarded from 10.10 to 10.20?  Do you see device announcements when you run `upnp -zs`?

> zp -H 10.20.0.6 eventlog this:

Is the host running homebridge multi-homed?  Unfortunately, unlike homebridge-zp, `zp` does not provide a way to specify the host and port of the listener.

> And http://10.10.0.11:1400/notify doesn’t even opens a webpage if I try to open it from the same subnet.

You did start homebridge before trying, didn’t you?  Could you please capture a debug log file and attach that (please do not copy/paste).  See https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by AlfaJackal** [comment]
> > And upnp -z this:
> 
> Not good. Is the UPnP search request forwarded from 10.10 to 10.20? Do you see device announcements when you run `upnp -zs`?

Nope, don't see anything if I run `upnp -zs`, just `listening on 0.0.0.0:1900` so I canceled it after a minute with STRG+C.

> > zp -H 10.20.0.6 eventlog this:
> 
> Is the host running homebridge multi-homed? Unfortunately, unlike homebridge-zp, `zp` does not provide a way to specify the host and port of the listener.

Just hosting a single home.

> > And http://10.10.0.11:1400/notify doesn’t even opens a webpage if I try to open it from the same subnet.
> 
> You did start homebridge before trying, didn’t you? Could you please capture a debug log file and attach that (please do not copy/paste). See https://github.com/ebaauw/homebridge-hue#debug-log-file.

Yep, I started homebridge before trying. Here is the log attached: 
[homebridge.log](https://github.com/ebaauw/homebridge-zp/files/3672598/homebridge.log)

**Comment by ebaauw** [comment]
> Just hosting a single home.

Checked the code: it tries to find a network interface on the same subnet as the zone player.

> Yep, I started homebridge before trying. Here is the log attached: homebridge.log

The listener isn't yet started; it only starts when the first (discovered) zone player is being configured.

> After some research, I think it is definately the upnp across vlans.

I'm afraid there's nothing I can do here.  Except, of course, the obvious suggestion to review your network segmentation.

**Comment by AlfaJackal** [comment]
Thank you! You did a lot for me because you just tried to help. Pretty impressive, also your knowledge! Keep it up doing things like this! 👍
