### ISSUE TITLE
ZP devices impersonating other accessories

### ISSUE THREAD

**Issue by Garywoo** [ebaauw/homebridge-zp#112]
Apologies in advance for this awful issue report.

A few days ago I noticed my RPI ran out of storage, and Homebridge stopped working correctly. I freed up the storage again, then updated Node. I then noticed that not all my Sonos speakers were showing up in Homekit. Some were there, but a few were missing.

I did some experiments and noticed that some other devices were appearing twice, i.e. some Hue compatible lights (connected via homebridge-hue) Only only one of these was behaving correctly when tapping on it. When toggling each of these duplicate lights and looking at the homebridge log output, I noticed that homebridge-hue was logging one of the lights actually turning on, and for the other light, homebridge-zp was reporting that I was turning on one of the missing Sonos speakers:
```
[11/15/2019, 00:35:14] [Hue] Shelf Lights: homekit on changed from 0 to 1
[11/15/2019, 00:35:17] [Hue] Shelf Lights: homekit on changed from 1 to 0
[11/15/2019, 00:35:23] [ZP] Lounge Shelf Sonos: On changed from false to true
[11/15/2019, 00:35:23] [ZP] Lounge Shelf Sonos: set On from true to false
```
My config has not changed from when everything was working great. It looks like this:
```
{
    "platform": "ZP",
    "service": "speaker",
    "brightness": true,
    "speakers": true,
    "searchTimeout": 15
}
```
I really don't know how it got like this. I'm fearing that I'll need to remove everything and start from scratch with homebridge, but i'm really hoping to avoid doing that. Any suggestions would be appreciated 😁

Here's a log of homebridge -D - [zp.log](https://github.com/ebaauw/homebridge-zp/files/3849348/zp.log)

**Comment by ebaauw** [comment]
I see nothing wrong in the log; homebridge-zp finds and communicates with the Launch Shelf Sonos alright.  My best guess: the `IdentifierCache` in the `persist` directory got corrupted.  This file maps (short) accessory, service, and characteristic IDs (used by HomeKit) to the (long) UUIDs (used by homebridge and the plugins).  This mapping is supposed to be constant (during the lifetime of the accessory being paired to HomeKit).

You did run `fsck` to check and repair the filesystem, didn’t you?  If you have a backup, you could try and restore `persist` (exit homebridge first).  If not, I fear the only remedy is to remove homebridge from HomeKit, wait for that change to propagate to all your iDevices, shutdown homebridge, delete `persist` and `accessories`, start homebridge, and spend a couple of hours redoing your HomeKit configuration.  You might want to make screenshots of your rooms, groups, scenes, automations, button actions before doing this.

**Comment by Garywoo** [comment]
Thanks for the advice. I tried `fsck` on startup, but nothing got picked up. I ended up restoring my my `persist` folder from a backup, and that resolved the problem. 

The only oddities now are the following log lines on startup:
```
1|homebridge  | [11/18/2019, 21:28:40] [ZP] Bathroom: warning: Identify: 2 listeners
1|homebridge  | [11/18/2019, 21:28:40] [ZP] Kitchen Sidekick: warning: Identify: 2 listeners
1|homebridge  | [11/18/2019, 21:28:40] [ZP] Kitchen: warning: Identify: 2 listeners
1|homebridge  | [11/18/2019, 21:28:40] [ZP] Living Room: warning: Identify: 2 listeners
1|homebridge  | [11/18/2019, 21:28:40] [ZP] Lounge Shelf: warning: Identify: 2 listeners
1|homebridge  | [11/18/2019, 21:28:40] [ZP] My Room: warning: Identify: 2 listeners
1|homebridge  | [11/18/2019, 21:28:40] [ZP] Spare Room: warning: Identify: 2 listeners
1|homebridge  | [11/18/2019, 21:28:40] [ZP] Utility Room: warning: Identify: 2 listeners
```
Is this normal?

**Comment by ebaauw** [comment]
I wouldn’t call this “normal”, but yes, this is expected for now.
