### ISSUE TITLE
Does this make adding a true speaker possible

### ISSUE THREAD

**Issue by adavison007** [ebaauw/homebridge-zp#116]
I know you don’t like this question, but had to ask...  

https://apple.news/ATnunA_-EQbeZswGvXKmYqA

**Comment by ebaauw** [comment]
I don't mind, but no, it doesn't change anything.  Apple's Home app and Siri only support the _Speaker_ service over HAP for video doorbell accessories.  Support of "true" speakers is through AIrPlay2, which has nothing to do with HomeKit.
