### ISSUE TITLE
Unsupported accessory  

### ISSUE THREAD

**Issue by martin072** [ebaauw/homebridge-zp#118]
Hi, I just installed your Homebridge Plugin, and it seems to work fine, I seen all my sonos devices and data in the homebridge log, however, my homekit app on my iOS device (13.3) says "Unsupported accessory"

Any idea why that is?

**Comment by ebaauw** [comment]
Not really.  Could you post a screenshot?  What does the accessory look like in Eve?  What's you config.json - how do you expose the Sonos players?

**Comment by martin072** [comment]
Hi, thanks for the answer. Leaving home now for a few days, will enable it again next week. I don't use Eve.. I use the standard apple homekit app. Config.json is as per you example, with a few other homebridge accessories like http-switch and http-dimmer. All works fine.  Sonos is on the same network as homebridge, and as mentioned, I did see all the updates scrolling by in the homebridge log (volume changes, radio /artist changes etc.), no errors.  It is just that the Apple Homekit App say "unsupported accessory". Running it on iOS 13.3 and also on a Mac with OS 10.15.2 it says the same..

**Comment by OfficialKaos** [comment]
That happens to me when I run the service as a speaker, I dont have this issue when I run the service as a light. 

This is mentioned in the configuration description please see copy and pasted snippet, the last sentence.

service | "switch" | Defines what type of service and volume characteristic homebridge-zp uses.  Possible values are: "switch" for Switch and Volume; "speaker" for Speaker and Volume; "light" for LightBulb and Brightness; and "fan" for Fan and Rotation Speed.  Selecting "light" or "fan" enables changing the Sonos volume from Siri and from Apple's Home app.  Selecting "speaker" is not supported by Apple's Home app.
-- | -- | --

**Comment by martin072** [comment]
Thanks, overlooked it, it's running now as a bulb.
