### ISSUE TITLE
Error when surround player is missing/powered down

### ISSUE THREAD

**Issue by BlackCydonian** [ebaauw/homebridge-zp#119]
Hi, 
after starting homebridge I get this log.
Thanks for your help.

> Dez 28 14:34:14 raspi homebridge[17524]: [2019-12-28 14:34:14] Homebridge is running on port 51826.
Dez 28 14:34:14 raspi homebridge[17524]: [2019-12-28 14:34:14] [ZP] error: RINCON_B8E93774C5D401400 [192.168.178.32]: {}
Dez 28 14:34:14 raspi homebridge[17524]: [2019-12-28 14:34:14] [ZP] error: RINCON_5CAAFD42776E01400 [192.168.178.28]: {}
Dez 28 14:34:14 raspi homebridge[17524]: [2019-12-28 14:34:14] [ZP] error: RINCON_5CAAFD42B81E01400 [192.168.178.27]: {}
Dez 28 14:34:14 raspi homebridge[17524]: (node:17524) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'zonePlayers' of undefined
Dez 28 14:34:14 raspi homebridge[17524]:     at ZpPlatform.logTopology (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:340:49)
Dez 28 14:34:14 raspi homebridge[17524]:     at ZpPlatform.createZpClient (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:288:14)
Dez 28 14:34:14 raspi homebridge[17524]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Dez 28 14:34:14 raspi homebridge[17524]: (node:17524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
Dez 28 14:34:14 raspi homebridge[17524]: (node:17524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Dez 28 14:34:17 raspi homebridge[17524]: [2019-12-28 14:34:17] [Config] Homebridge Config UI X v4.6.7 is listening on :: port 8080
Dez 28 14:34:45 raspi homebridge[17524]: [2019-12-28 14:34:45] [ZP] error: TypeError: Cannot read property 'zonePlayers' of undefined
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform.heartbeat (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:133:48)
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform.emit (events.js:210:5)
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform.emit (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Delegate.js:148:13)
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform._heartbeat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:295:10)
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform._beat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:281:18)
Dez 28 14:34:45 raspi homebridge[17524]:     at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:269:12)
Dez 28 14:34:45 raspi homebridge[17524]:     at listOnTimeout (internal/timers.js:531:17)
Dez 28 14:34:45 raspi homebridge[17524]:     at processTimers (internal/timers.js:475:7)
Dez 28 14:34:45 raspi homebridge[17524]: [2019-12-28 14:34:45] [ZP] error: TypeError: Cannot read property 'zonePlayers' of undefined
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform.heartbeat (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:133:48)
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform.emit (events.js:210:5)
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform.emit (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Delegate.js:148:13)
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform._heartbeat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:295:10)
Dez 28 14:34:45 raspi homebridge[17524]:     at ZpPlatform._beat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:281:18)
Dez 28 14:34:45 raspi homebridge[17524]:     at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:269:12)
Dez 28 14:34:45 raspi homebridge[17524]:     at listOnTimeout (internal/timers.js:531:17)
Dez 28 14:34:45 raspi homebridge[17524]:     at processTimers (internal/timers.js:475:7)

**Comment by ebaauw** [comment]
Please capture and attach a full debug log, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by BlackCydonian** [comment]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-zp/files/4007319/homebridge.log.gz)

**Comment by ebaauw** [comment]
Thanks.  Looks like it took you some time to upgrade NodeJS and get homebridge-config-ui-x recompiled, but in the end it seems OK.

- homebridge-zp finds three zone players by UPnP: your PlayBar and left surround Play:1 in _Wohen_ and a Play:1 in _Küche_.  I'm slightly worried that it doesn't find the right surround.
  ```
  Dez 28 19:32:20 raspi homebridge[20261]: [2019-12-28 19:32:20] [ZP] upnp: listening on 0.0.0.0:1900
  Dez 28 19:32:20 raspi homebridge[20261]: [2019-12-28 19:32:20] [ZP] upnp: searching on 0.0.0.0:59493
  Dez 28 19:32:20 raspi homebridge[20261]: [2019-12-28 19:32:20] [ZP] upnp: found RINCON_B8E93774C5D401400 at 192.168.178.32
  Dez 28 19:32:21 raspi homebridge[20261]: [2019-12-28 19:32:21] [ZP] upnp: found RINCON_5CAAFD42776E01400 at 192.168.178.28
  Dez 28 19:32:21 raspi homebridge[20261]: [2019-12-28 19:32:21] [ZP] upnp: found RINCON_5CAAFD42B81E01400 at 192.168.178.27
  Dez 28 19:32:25 raspi homebridge[20261]: [2019-12-28 19:32:25] [ZP] upnp: search done
   ```
- It's probing the zone players as expected, but something goes wrong.  Unfortunately no error message?!
   ```
  Dez 28 19:32:20 raspi homebridge[20261]: [2019-12-28 19:32:20] [ZP] RINCON_B8E93774C5D401400 [192.168.178.32]: probing (1 jobs)...
  Dez 28 19:32:20 raspi homebridge[20261]: [2019-12-28 19:32:20] [ZP] RINCON_B8E93774C5D401400 [192.168.178.32]: request 1: GET /xml/device_description.xml
  Dez 28 19:32:20 raspi homebridge[20261]: [2019-12-28 19:32:20] [ZP] RINCON_B8E93774C5D401400 [192.168.178.32]: request 1: status 200
  Dez 28 19:32:21 raspi homebridge[20261]: [2019-12-28 19:32:21] [ZP] RINCON_B8E93774C5D401400 [192.168.178.32]: request 2: POST /ZoneGroupTopology/Control GetZoneGroupState
  Dez 28 19:32:21 raspi homebridge[20261]: [2019-12-28 19:32:21] [ZP] RINCON_B8E93774C5D401400 [192.168.178.32]: request 2: status 200
  Dez 28 19:32:21 raspi homebridge[20261]: [2019-12-28 19:32:21] [ZP] RINCON_B8E93774C5D401400 [192.168.178.32]: Wohnen: Sonos Playbar (S9) v10.6
  Dez 28 19:32:21 raspi homebridge[20261]: [2019-12-28 19:32:21] [ZP] error: RINCON_B8E93774C5D401400 [192.168.178.32]: {}
  Dez 28 19:32:21 raspi homebridge[20261]: [2019-12-28 19:32:21] [ZP] RINCON_B8E93774C5D401400 [192.168.178.32]: probing failed (2 jobs remaining)
  ```
- The same sequence for the other two zoneplayers.
- The other errors are a result of homebridge-zp not having initialised any accessory because of the failed probing. 
  ```
  Dez 28 19:32:21 raspi homebridge[20261]: (node:20261) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'zonePlayers' of undefined
  Dez 28 19:32:21 raspi homebridge[20261]:     at ZpPlatform.logTopology (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:340:49)
  Dez 28 19:32:21 raspi homebridge[20261]:     at ZpPlatform.createZpClient (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:288:14)
  Dez 28 19:32:21 raspi homebridge[20261]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  Dez 28 19:32:21 raspi homebridge[20261]: (node:20261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
  Dez 28 19:32:21 raspi homebridge[20261]: (node:20261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ```
  Strictly speaking the unhandled promise rejection is bug.
- Consecutive errors seem to be handled OK, though:
  ```
  Dez 28 19:32:51 raspi homebridge[20261]: [2019-12-28 19:32:51] [ZP] error: TypeError: Cannot read property 'zonePlayers' of undefined
  Dez 28 19:32:51 raspi homebridge[20261]:     at ZpPlatform.heartbeat (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:133:48)
  Dez 28 19:32:51 raspi homebridge[20261]:     at ZpPlatform.emit (events.js:210:5)
  Dez 28 19:32:51 raspi homebridge[20261]:     at ZpPlatform.emit (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Delegate.js:148:13)
  Dez 28 19:32:51 raspi homebridge[20261]:     at ZpPlatform._heartbeat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:295:10)
  Dez 28 19:32:51 raspi homebridge[20261]:     at ZpPlatform._beat (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:281:18)
  Dez 28 19:32:51 raspi homebridge[20261]:     at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:269:12)
  Dez 28 19:32:51 raspi homebridge[20261]:     at listOnTimeout (internal/timers.js:531:17)
  Dez 28 19:32:51 raspi homebridge[20261]:     at processTimers (internal/timers.js:475:7)
  ```
I have no clue why the probing fails.  You seem to be using same versions of NodeJS, homebridge, homebridge-zp, and Sonos firmware as I do.  Can you please run the following command and list the output here?
```
$ zp -H 192.168.178.32 topology -v
```
If the command works, could you try and run homebridge without the other plugins enabled?  I run homebridge-config.ui-x without any issues, but I'm unfamiliar with the Harmony Hub/Sony plugin.

If the command results in a similar error as homebridge-zp, could you then run it with a ridiculous level of debugging enabled.
```
$ DEBUG=* zp -H 192.168.178.32 topology -v
```

**Comment by BlackCydonian** [comment]
First of all, thank you so much for your quick response and in deep log file analysis.
And second: I feel so ashame...
As you wondered about the missing Play:1 in „Wohnen“, I checked the devices.
The second Play:1 simply was not attached to power.

After connecting to power and restarting homebridge everything worked fine.

So you can close this issue - and at best forget my post ;-)

Best regards,
Marco

**Comment by ebaauw** [comment]
> The second Play:1 simply was not attached to power.

Hm, then homebridge-zp apparently doesn't understand the topology when one of the surround players is powered down/missing.  I'll have to do some tests to see what's going on in detail, but I still think it's a bug.
