### ISSUE TITLE
Unresponsive TV accessories in HomeKit after disabling How / TV setup

### ISSUE THREAD

**Issue by HanSooloo** [ebaauw/homebridge-zp#121]
I had enabled the TV service for my 2 Sonos speakers before, but found no use for them.  So, I disabled them today.
However, even after disabling, my HomeKit app on my iPhone still shows them in "No Response" state.
What do I have to do to get them removed?  Shouldn't disabling the service remove them from HomeKit already?

**Comment by ebaauw** [comment]
No.  TV accessories are standalone accessories which need to paired to and removed from HomeKit individually.

**Comment by HanSooloo** [comment]
Ah! That helps explain it ... thanks for the clarification.  I am going to remove them manually.
