### ISSUE TITLE
Sonos devices appear in log but not accessories added

### ISSUE THREAD

**Issue by PedroRA561** [ebaauw/homebridge-zp#124]
Hello,

been trying to get this plugin to work but without much success ... not sure what is wrong.

On the log i can see the devices being detected but afterwards no accessory appears. Maybe i am missing something on the config.

After the detection i am also getting an error:
[Sonos] RINCON_347Exxxxx01400 [Office]: associated zone player
[Sonos] found 4 zone players in 4 zones
[Sonos] ├─ Bedroom
[Sonos] │  └─ RINCON_48A6BxxxxxC01400 [Bedroom]: Sonos One SL (S22) (master, airPlay)
[Sonos] ├─ Dining Room
[Sonos] │  └─ RINCON_347E5CxxxxxC01400 [Dining Room]: Sonos Play:1 (S12) (master)
[Sonos] ├─ Family Room
[Sonos] │  └─ RINCON_347E5CxxxxxC01400 [Family Room]: Sonos Playbar (S9) (master, tvIn)
[Sonos] └─ Office
[Sonos]    └─ RINCON_347E5xxxxx001400 [Office]: Sonos Play:1 (S12) (master)
[Sonos] Bedroom Sonos: remove stale characteristic Volume
[Sonos] Bedroom Speakers: set Volume Change to 0
(node:6630) UnhandledPromiseRejectionWarning: TypeError: events.once is not a function
    at ZpPlatform.logTopology (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:421:28)
    at ZpPlatform.createZpClient (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:292:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6630) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3) 

my config is:
{
            "name": "Sonos",
            "brightness": true,
            "service": "speaker",
            "speakers": true,
            "platform": "ZP"
        }

**Comment by ebaauw** [comment]
You’re running an old version of NodeJS that doesn’t support `events.once()`.

**Comment by PedroRA561** [comment]
Actually I am running nose v10.15.2. I am a bit of a beginner here so ... should I downgrade or upgrade node ?

**Comment by PedroRA561** [comment]
Jus saw the updates readme. D
