### ISSUE TITLE
cli zp issue

### ISSUE THREAD

**Issue by johnluber** [ebaauw/homebridge-zp#126]
Thank you for addressing Issue 125 so quickly!

I was playing with the zp cli tool and it is extremely useful.  However, having some difficulty playing Sonos Playlists.

If I browse a zone player I get results:

zp -H 192.168.1.128 browse  SQ:
{
  "Free Spirit": {
    "browse": "SQ:5",
    "uri": "file:///jffs/settings/savedqueues.rsq#5"
  },
  "Love Songs": {
    "browse": "SQ:4",
    "uri": "file:///jffs/settings/savedqueues.rsq#4"
  }
}

But then issuing:  

zp -H 192.168.1.128 play file:///jffs/settings/savedqueues.rsq#4

I get:

zp play: error: POST /MediaRenderer/AVTransport/Control: http status 500

AM I doing something wrong?  I am able to get Q:0 and FV:2 to play when I send the uri

**Comment by johnluber** [comment]
Never mind.  I think I've figured it out.

I need to queue the uri first and then play it.

Sorry to bother you.  I love this cli utility.

**Comment by djsunrise19** [comment]
Short Question here: I'm using the standard config, everything works fine but I cannot use the cli. I always get: `zp: error: connect ECONNREFUSED 192.168.1.130:1400`. Where is my fault?

Config:
`        {
            "name": "Sonos",
            "alarms": true,
            "brightness": true,
            "service": "light",
            "platform": "ZP",
            "port": "1400"
        }`

Thanks!

**Comment by ebaauw** [comment]
`ECONNREFUSED` generally means no-one is listening to the port, probably because you're not connecting to a Sonos zone player.  Are you sure this is the IP address of one of your zone players?  What does your web browser display when you open `http://192.168.1.130:1400/status/zp`?

**Comment by djsunrise19** [comment]
Thank you for answering! Same Problem: `ERR_CONNECTION_REFUSED`. But I'm using all my speakers in Homekit and it works perfect. Homebridge log is fine, too:

`[2020-2-8 15:06:24] [Sonos] Küche Sonos: set On from true to false
[2020-2-8 15:06:24] [Sonos] Studio Sonos: On changed from false to true
[2020-2-8 15:06:26] [Sonos] Bad Sonos: set On from false to true
[2020-2-8 15:06:26] [Sonos] Flur Sonos: set On from false to true
[2020-2-8 15:06:26] [Sonos] Küche Sonos: set On from false to true`
