### ISSUE TITLE
warning: npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function

### ISSUE THREAD

**Issue by daberlin** [ebaauw/homebridge-zp#128]
Hi,
since I upgraded to the latest ver, I get the following warning (once during startup, as far as I can see):

Mär 16 17:20:50 pi-home homebridge[1711]: [2020-3-16 17:20:50] [Sonos] warning: npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
Mär 16 17:20:50 pi-home homebridge[1711]:     at checkListener (events.js:109:11)
Mär 16 17:20:50 pi-home homebridge[1711]:     at ClientRequest.once (events.js:431:3)
Mär 16 17:20:50 pi-home homebridge[1711]:     at new ClientRequest (_http_client.js:194:10)
Mär 16 17:20:50 pi-home homebridge[1711]:     at Object.request (https.js:314:10)
Mär 16 17:20:50 pi-home homebridge[1711]:     at Object.request (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/agent-base/patch-core.js:25:22)
Mär 16 17:20:50 pi-home homebridge[1711]:     at HttpClient.request (/usr/lib/node_modules/homebridge-lib/lib/HttpClient.js:226:32)
Mär 16 17:20:50 pi-home homebridge[1711]:     at HttpClient.get (/usr/lib/node_modules/homebridge-lib/lib/HttpClient.js:136:17)
Mär 16 17:20:50 pi-home homebridge[1711]:     at ZpPlatform._checkLatest (/usr/lib/node_modules/homebridge-lib/lib/Platform.js:380:42)
Mär 16 17:20:50 pi-home homebridge[1711]:     at ZpPlatform._heartbeat (/usr/lib/node_modules/homebridge-lib/lib/Platform.js:290:12)
Mär 16 17:20:50 pi-home homebridge[1711]:     at ZpPlatform._beat (/usr/lib/node_modules/homebridge-lib/lib/Platform.js:284:42)

**Comment by ebaauw** [comment]
I now query the NPM registry over SSL, but something is breaking https.  Either an old version of NodeJS (see https://github.com/ebaauw/homebridge-hue/issues/660), or (a dependency loaded by) another plugin, see https://github.com/ebaauw/homebridge-hue/issues/652.

Apart from not being notified when a new version has been published, homebridge-zp should function normally.

**Comment by Djelibeybi** [comment]
Do you have the `homebridge-fritz-platform` plugin installed? A user of my plugin had exactly the same problem and he narrowed it down to that plugin causing the problem.

**Comment by daberlin** [comment]
I have that plugin installed as well.
Is there any solution?

**Comment by ebaauw** [comment]
Don't run homebridge-fritz-platform in the same Homebridge instance as homebridge-zp.  Or use a different plugin for Fritz, see https://github.com/ebaauw/homebridge-hue/issues/629#issuecomment-592588385.

**Comment by daberlin** [comment]
Found a solution: remove homebridge-fritz-platform (rm -rf .../node_modules/homebridge-fritz-platform), then reinstall with npm.
This updates the dependency "agent-base" to a version that does not break https.
