### ISSUE TITLE
1.0.26 Crashes Homekit (hoobs) See screen shot.

### ISSUE THREAD

**Issue by adavison007** [ebaauw/homebridge-zp#129]
<img width="1119" alt="Screenshot 2020-04-11 at 10 18 30" src="https://user-images.githubusercontent.com/47482260/79040096-0ed4ba80-7bde-11ea-9f39-244a60c993fd.png">

**Comment by adavison007** [comment]
@ebaauw Just rolled back to 1.0.25 and that version works fine

**Comment by ebaauw** [comment]
I don't understand hoobs and I don't recommend it.  There's a message `Error Loading Plugin "homebridge-zp"` earlier on, presumably meaning that hoobs hasn't loaded the plugin.  I don't know where this error comes from (it isn't issued by homebridge-zp nor by Homebridge), nor what it means.  Better contact hoobs support.

**Comment by adavison007** [comment]
OK, many thanks for looking and letting me know. I’ll speak to hoobs.

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 11 Apr 2020, at 10:58, Erik Baauw <notifications@github.com> wrote:


I don't understand hoobs and I don't recommend it. There's a message Error Loading Plugin "homebridge-zp" earlier on, presumably meaning that hoobs hasn't loaded the plugin. I don't know where this error comes from (it isn't issued by homebridge-zp nor by Homebridge), nor what it means. Better contact hoobs support.

**Comment by cgilis** [comment]
> @ebaauw Just rolled back to 1.0.25 and that version works fine

How do you do this in HOOBS?

**Comment by adavison007** [comment]
> > @ebaauw Just rolled back to 1.0.25 and that version works fine
> 
> How do you do this in HOOBS?

Go to Terminal in hoobs...

Then type cd /home/hoobs/.hoobs

Then type sudo npm install --save homebridge-zp@1.0.25

**Comment by cgilis** [comment]
> > > @ebaauw Just rolled back to 1.0.25 and that version works fine
> > 
> > 
> > How do you do this in HOOBS?
> 
> @cgilis Go to Terminal in hoobs...
> 
> Then type cd /home/hoobs/.hoobs
> 
> Then type sudo npm install --save homebridge-zp@1.0.25

Thx! That worked!
Btw to do this on a Synology (docker): cd ../

Result in terminal:
/hoobs/etc # cd ../
/hoobs #
