### ISSUE TITLE
homebridge 1.0.0 compatibility

### ISSUE THREAD

**Issue by fredthedorfman** [ebaauw/homebridge-zp#133]
#### Issue

plugin thinks the homebridge installation ver 1.0.0 is older than 0.4.53, plugin won’t run which causes homebridge to no longer run.

#### Log Messages

```
ERROR LOADING PLUGIN homebridge-zp:
Error: Plugin /usr/local/lib/node_modules/homebridge-zp requires a HomeBridge version of ~0.4.53 which does not satisfy the current HomeBridge version of 1.0.0. You may need to upgrade your installation of HomeBridge.
```

**Comment by ebaauw** [comment]
Upgrade homebridge-zp to v1.0.27, see https://github.com/ebaauw/homebridge-zp/releases.  I’ll set this version to the `latest` later today, when I’ll be at my computer.
