### ISSUE TITLE
Cannot set property after zp update

### ISSUE THREAD

**Issue by mikeleijs** [ebaauw/homebridge-zp#138]
Hey! I’ve updated the plugin to the last version and now my players don’t load, only 1 of 3 after a while. The rest is unreachable while no change is made in the speakers or ip’s.

![26206DC5-935E-4E27-A9CC-73E4C66175A6](https://user-images.githubusercontent.com/54823530/82768035-81b39100-9e2c-11ea-9c74-8461b94ff075.png)

**Comment by ebaauw** [comment]
What version did you upgrade from?

Could you please capture and attach a debug log file?  See https://github.com/ebaauw/homebridge-zp#debug-log-file.

**Comment by mikeleijs** [comment]
[homebridge.log](https://github.com/ebaauw/homebridge-zp/files/4676280/homebridge.log)

Does this help?

**Comment by mikeleijs** [comment]
I've updated from the last most recent version to the new V1.0.32. Zoneplayer app and sonos app see all speakers correctly, it's just the homebridge plugin that doesn't see them correctly. After a while my "Bar" zone/speakers pops up, but the rest doesn't

**Comment by ebaauw** [comment]
> Does this help?

Sorry, will have to wait till this evening to look at it - work's calling.

**Comment by ebaauw** [comment]
A `TypeError` surely is a bug, but in this case just a symptom of an underlying problem, I'm afraid.  I see an awful lot of other error messages (from other plugins), indicating network connectivity issues.  I need the debug log messages (from `homebridge -D`) to understand what's happening.  I think Homebridge ZP receives incomplete info from the zone players.

Could you capture the output of `zp -H 192.168.178.25 topology -v`?  If that also causes an error, could you try `DEBUG=* zp -H 192.168.178.25 topology -v`.  This will produce a ludicrous
amount of debug messages.

**Comment by mikeleijs** [comment]
The other errors come from Homebridge tv’s, they always give those errors when switched off. Network is all fine, 420mbit continuous without downtime. Sonos is playing non stop too without any problem. But i’ll try the commands and will upload The file

**Comment by mikeleijs** [comment]
[Naamloos.docx](https://github.com/ebaauw/homebridge-zp/files/4678535/Naamloos.docx)

**Comment by ebaauw** [comment]
That's not the full output.  Also what were you thinking creating a Word file for this?!

Looks like the Sub for the Bar is missing from the topology, but still mentioned in the channel map.  Does it appear in the Sonos app?

> Network is all fine, 420mbit continuous without downtime.

I meant your local network, not your Internet connection.

**Comment by mikeleijs** [comment]
It started working again, i've used the homebridge-sonos plugin in the meantime, that worked fine from the start. And after the last nodejs update your plugin worked fine again too. Sorry that i ain't a tech expert. I just try to give what you've asked for, no need to get offended here for just me trying...

**Comment by ebaauw** [comment]
> It started working again

That's good.

> And after the last nodejs update your plugin worked fine again too. 

I don't think the error has anything to do with any version update.  I (hopefully) fixed the `TypeError`, but cannot fix the missing zone player.

**Comment by ebaauw** [comment]
Fix for `TypeError` in v1.0.34.
