### ISSUE TITLE
siri commands

### ISSUE THREAD

**Issue by Pilschat** [ebaauw/homebridge-zp#14]
Hello i just installed the homebridge-zp with this config

{
      "platform": "ZP",
      "name": "ZP",
      "service": "speaker",
      "brightness": true,
      "speakers": true
    }

When it installs, i see it finds all my speakers and groups.

Question 1:
But when i am in my dutch homekit-app "woning" (basic app from apple), there is presented a button called "Playbar TV sonos", but i cannot click on it. It then says it is not supported.

Question 2: How can or should i call it from within siri. I tried the dutch sentences"zet the sonos aan", "zet speaker aan", "zet playbar tv aan" etc.

But nothing happens.

What do i do wrong?

**Comment by ebaauw** [comment]
See the README: Neither the iOS built-in app nor Siri supports the Speaker service.  You either need to change config.json to map the Sonos to a service that is supported by these, or use a different HomeKit app.

**Comment by Pilschat** [comment]
Ok, I am quit new on the homebridge system, so maybe it is a silly question. But can you tell me how i can map it then to a service so it will work with an app and with siri?
Because the main reason i installed the homebridge is that i can use it thru siri or the home app. I use the built and the Insteon app.

And if this is not working, can you explain what i can do with this homebridge-zp plugin?

Hope you can help me out, thanks

**Comment by ebaauw** [comment]
Zoals beschreven in de README: in config.json kun je aangeven via welke service homebridge-zp de Sonos aan HomeKit bekend maakt.  Je hebt nu `"service": "speaker"` staan, als je die regel eruit haalt, of verandert in de default `"service": "switch"` snappen de Woning app en Siri het wel.
