### ISSUE TITLE
Feature request: Stateless button for custom sounds/alerts

### ISSUE THREAD

**Issue by dxdc** [ebaauw/homebridge-zp#141]
#### Issue
Thanks for your work on this plugin!

Had an idea to expose custom sounds for individual Sonos speakers. This could be exposed as stateless buttons within each accessory, and used to trigger specific alerts for automations. An `excludeZones` array could be used to limit which zones get these custom sound buttons.

```js
  "playSounds": [
    {
      "name": "DunDun", 
      "restorePrevious": true, 
      "url": "https://www.myinstants.com/media/sounds/dun_dun_1.mp3", 
      "excludeZones": [], 
      "volume": 15
    },
    {
      "name": "Wrong Answer", 
      "restorePrevious": true, 
      "url": "https://www.myinstants.com/media/sounds/wrong-answer-sound-effect.mp3", 
      "excludeZones": ["Kitchen"], 
      "volume": 20
    }
  ]
```

Here would be the workflow:
1. Save current Sonos play URL/volume/play state
2. Pause Sonos (if playing)
3. Set desired volume and play desired URL - I guess custom Spotify playlists could be loaded here too?
4. After track finishes* (this may need some more thought as to how this could be calculated, maybe instead it should just reset after X seconds), restore previous playlist state, and resume playing if it was previously playing. (This is the `restorePrevious` parameter)

There are a number of cool use cases I can think of:

1. Automatically load Spotify playlist as part of a scene
2. Play custom alerts when things happen - e.g., announce who has arrived or left

#### Log Messages

```
```

**Comment by ebaauw** [comment]
I like the idea, been fantasising about something like this for quite some time.  My use case would be to sound an alarm (in case of smoke, fire, door or window left open, ...), maybe using text to speech.  Problem is, I don’t know how to save and restore the current zone player state.  Another challenge is that you cannot push audio to the zone player; it needs to be served (as in your example) so the zone player can retrieve it itself.  And finally, I don’t want to introduce a dependency on a cloud service for text to speech.  macOS has a local capability, but I don’t think most other OSs do.

Not a big fan of lengthy config.json setups.  

To play a Spotify playlist from a HomeKit scene, add it to the Sonos favourites, and include the corresponding _Active Identifier_ value in the scene.  Of course you need to use Eve, or another decent HomeKit app, to create the scene, as Home doesn’t support all of HomeKit.

**Comment by dxdc** [comment]
Thanks @ebaauw - appreciate you considering this suggestion. On account of the `zp` cli tool (and `sonos` npm library), I can already do most of this already. I have tested it in my set up, I'll explain.

`currentTrack` and `currentVolume` can be retrieved from the `sonos` npm library, which includes the URL. Your plugin already handles whether or not the player is running or not.

e.g.
```
Title: You on My Mind
Album: Piccadilly Perfume
Artist: Jye
URI: x-sonos-vli:RINCON_347E5CC90D5801400:2,spotify:1442c2333e972eee32b9c486f5f519c5
```

I don't know how this translates to Spotify playlists though. If this is too complicated, the functionality could be simplified to an override setting in config.json.

The logic would work like this (pseudo-code):

```js
if (zone.isPlaying() && !override) {
    return;
}
zone.stop();
const savedVol = zone.getVolume();
zone.setVolume(config.volume);
zone.play(config.url);
setTimeout(function() {
    if (!zone.isPlaying()) {
        zone.setVolume(savedVol);
    }
}, config.timeout * 1000);

```

> Not a big fan of lengthy config.json setups.

The long `config.json` doesn't bother me at all...  mine is already 500+ lines. There are a lot of plugins that require very long setups.

Also, exposing a stateless button is adaptable based on this code:
https://github.com/nfarina/homebridge-dummy/blob/master/index.js

> Of course you need to use Eve, or another decent HomeKit app, to create the scene, as Home doesn’t support all of HomeKit.

Eve is fine I guess, but I can run this from NodeRED (far more powerful) using the cli tool. I have a local web server set up and could stash a number of mp3's there for instance, and expect most people could do the same?

I like the idea of text to speech for the cases you mentioned. I have some simple code that uses Google API's to make MP3s. I think there are a few ways to handle it, but it might be simplest to just pre-generate the MP3's you need for all cases and serve them off of the local web server. Trying to generate these on demand without something like NodeRED is complicated (and probably not needed?), especially if one of the alerts is for a downed external internet connection.

Although, maybe these could all be pre-generated at start up and cached based on the md5 hash of the desired string?

Anyway, something to think about. I'm going to continue working with NodeRED to try and develop this, but I thought it could be a great addition. I got inspired from the new chime feature in homebridge-ring that allows you to play the standard motion/doorbell alert sounds on demand. But, rather than buying a lot of chimes, one could just play an infinite library of alerts via their Sonos.

**Comment by dxdc** [comment]
Btw, check this out! This play/restore logic already exists!

https://github.com/bencevans/node-sonos/blob/37ab7653e7dec12303ee1a29989aee350850a2da/lib/sonos.js#L856-L923

**Comment by dxdc** [comment]
I also found this:
https://flows.nodered.org/node/node-red-contrib-sonospollytts

I think it solves the issue for TTS. Also, there are a few node-red-contrib sonos plugins that use `node-sonos` npm package and can use the playNotification command. I'm going to experiment with those as well.

Perhaps a much simpler path forward?
