### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by thorstenman** [ebaauw/homebridge-zp#142]
Constantly getting this message: 
[Sonos] warning: npm registry: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
Combined with:
[Sonos] <Speaker> Sonos: error: TypeError: Cannot read property 'zpClient' of null

**Comment by ebaauw** [comment]
Another plugin is breaking https.  See https://github.com/ebaauw/homebridge-zp/issues/128.
