### ISSUE TITLE
Feature request:  add brightness control for Sonos as a light

### ISSUE THREAD

**Issue by johnluber** [ebaauw/homebridge-zp#143]
First, love this plug-in.  I've been using it for several years and it's among the very best!  I recently discovered the cli and that makes it even better.

Maybe I'm using the plug-in wrong, but I use brightness for volume control and via small hack am able to do so using both the Home app and Siri controls.

What I do is specify the Sonos speakers as light bulbs which are dimmable and make a small chance to ZpPlatform.js.  I add "|| this.config.service == 'light'" to the conditions on line 118.

If I'm using the service incorrectly please tell me how to do it better.  If not, would you consider adding this small change to the base code?

Thanks and great plug-in!

**Comment by ebaauw** [comment]
I don't understand why you need the hack.  If you set `"service": "light"`, Homebridge ZP already uses _Brightness_ for volume control.
https://github.com/ebaauw/homebridge-zp/blob/d61012190ec060defc5e9c4ed02fd7967c0f1bb5/lib/ZpPlatform.js#L97-L100

**Comment by johnluber** [comment]
You are, of course, correct.  :). I tested it and it works as you said.  Not sure why/how I ever got on the path of the change.  Been doing it for a long while now.  And, now I don't need to any longer.

Thanks for the assist!
