### ISSUE TITLE
TV-Input shows accessory as always on

### ISSUE THREAD

**Issue by m-ruhl** [ebaauw/homebridge-zp#148]
Hi,

I have the Sonos Arc and I want to automate stuff if the Arc is on or not.. for example power on/off devices..

This works well in the plug-in for music.. but if the TV input is selected on the Arc.. the accessory in HomeKit is always on whether something is playing or the TV even on.

Is there a way to improve this?

Thanks
Michael

**Comment by ebaauw** [comment]
Sonos doesn't support _Play_/_Pause_ when on TV input.  The PlayBar, and, I assume the Arc as well, does report whether it sees any signal on the TV input.  Homebridge ZP exposes this as the custom _TV_ characteristic.  You'll need a decent HomeKit app like Eve to use custom characteristics, but other than that it works quite well.  I use it to dim my lights and turn up the PlayBar volume automatically, when turning on the TV (using the traditional TV remote).  I've configured the PlayBar to switch to TV input when it detects a signal.  When the TV is turned off (again using the traditional TV remote), or no longer sending a signal, I un-dim the lights, lower the PlayBar volume and switch the PlayBar back to the radio.

**Comment by m-ruhl** [comment]
Thanks.. this works out great 👍
