### ISSUE TITLE
Using node.js 14.15.1 LTS causes a warning

### ISSUE THREAD

**Issue by Zer0x00** [ebaauw/homebridge-zp#149]
#### Issue
While using node.js 14.15.1 with the latest security fix instead of 14.15.0 (both LTS) causes a warning to appear.

#### Log Messages

```
[Sonos] warning: 14.15.1: not using recommended node v14.15.0 LTS
```

#### Debug Files

not needed

**Comment by ebaauw** [comment]
In v.1.1.1.
