### ISSUE TITLE
Speakers not exposed

### ISSUE THREAD

**Issue by crlppr** [ebaauw/homebridge-zp#15]
Hello, 

I have installed the all these components in a Rasperry PI model B, but even when the homebridge is up and running and seems (reviewing the debugging file) that speakers have been found I can not see in the iPhone Home App. 

Could you please let me know what could we doing wrongly or what still pending?

Attached you can find the config and log file. 

Thanks in Advance
Cris.

[config.json.txt](https://github.com/ebaauw/homebridge-zp/files/736364/config.json.txt)
[logfile.txt](https://github.com/ebaauw/homebridge-zp/files/736365/logfile.txt)

**Comment by ebaauw** [comment]
> [2017-01-27 22:47:57] [ZP] Initializing ZP platform...
[2017-01-27 22:47:57] [ZP] homebridge-zp v0.1.6, node v6.9.1, homebridge v2.1
[2017-01-27 22:47:57] [ZP] listening on http://192.168.1.10:42794/notify
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
...                      
[2017-01-27 22:47:59] Homebridge is running on port 39419.
[2017-01-27 22:48:00] [ZP] Cocina: setup ZPS3 player RINCON_000E5873C1BA01400 at 192.168.1.114:1400

It looks like homebridge is loading before homebridge-zp has initialised and announced the accessories for the Sonos players to homebridge.  The messages that homebridge-zp found the player should appear before the `Homebridge is running on port 39419` message.

I haven't seen this before and, frankly, have no idea what's causing this.  What version of homebridge are you running?  (the listed v2.1 is the API version of homebridge).
