### ISSUE TITLE
Request: Make /notify available consumable as a JSON object

### ISSUE THREAD

**Issue by sokulski** [ebaauw/homebridge-zp#150]
Hi there!

Recently installed this package for Homebridge and I've been impressed with how easy it is to get control of Sonos thanks to your hard work.

One thing that I especially like is the CLI. I had experimented with node-sonos before, but to have a cLI that runs alongside Homebridge is really great.

The thing that would make it better, in my opinion, is an ability to discover devices. Right now, I'm looking at the http://192.168.X.X:40973/notify to see updates. But if that URL could be made available as a JSON object, say, that would be pretty powerful too.

Not sure what others are doing to get the current IP of a ZonePlayer for automation. Perhaps there's another answer I'm overlooking.

**Comment by ebaauw** [comment]
Try `upnp -z` to see the UPnP announcements.  `upnp` is included in homebridge-lib, which is included in homebridge-zp.  I used to create a symlink for it, just as for `zp`, but `npm` doesn’t like that anymore.  You should be able to start it using `npx`.

**Comment by sokulski** [comment]
Understood. Thanks for the super fast reply. I'll look at using upnp as a means of collecting this info.
