### ISSUE TITLE
Speakers still appear after removing plug-in

### ISSUE THREAD

**Issue by rwgunther** [ebaauw/homebridge-zp#151]
#### Issue

I've uninstalled the ZP plug-in, but the speakers still appear in Homebridge (two tiles for each, actually, with different names), and they appear in my HomeKit db (in Home and other apps). I can't remove them.
![Screen Shot 2020-11-26 at 12 46 11](https://user-images.githubusercontent.com/68545697/100380774-7d3b8100-2fe5-11eb-90d7-0e45b1741bc9.png)
![IMG_63DA3A22059F-1](https://user-images.githubusercontent.com/68545697/100380789-875d7f80-2fe5-11eb-8d88-f0f6f2a2dad8.jpeg)
#### Log Messages

These are the log entries for the orphaned speakers
```
[11/26/2020, 12:33:55 PM] Failed to find plugin to handle accessory Deck
[11/26/2020, 12:33:55 PM] Failed to find plugin to handle accessory Edward's Office
[11/26/2020, 12:33:55 PM] Failed to find plugin to handle accessory Gym
[11/26/2020, 12:33:55 PM] Failed to find plugin to handle accessory House Speakers
[11/26/2020, 12:33:55 PM] Failed to find plugin to handle accessory Sunroom L
```
There are no log entries for ZP. I just rebooted, and still no straggling log entries indicating any ZP activity. ZP is not installed anymore.

**Comment by ebaauw** [comment]
What version of Homebridge are you running?  It should remove accessories for which no plugin is loaded automatically with recent versions, unless you started it with   `-K`.  Start `homebridge -R` on older versions.

**Comment by rwgunther** [comment]
AHA! Thank you, @ebaauw. I apologize for gumming up the works here with my noob issue! That was exactly the problem. I don't know how that was set that way.
