### ISSUE TITLE
many DNS querys to multiple external IPs after activating the ZP Plugin on Homebridge

### ISSUE THREAD

**Issue by nbunbu** [ebaauw/homebridge-zp#152]
#### Issue
I noticed on my Pihole, what is acting as a DNS relay, many DNS query after I finalized my Homebridge Server.
After some investigation I found out that the ZP Sonos Plugin is creating this DNS request.
And I'm talking about a couple of 100k DNS request in just half a day to at least up to 200 different external IPs what in some cases didn't exist

How did I found this out, I change the Homebridge to a static IP with a static DNS server setting inside
I choosed one time a wrong internal DNS Server IP and could see that the ZP Sonos plugin is creating Error messages inside the Homebridge log

Question is now, why is Sonos doing this and is it possible to stop this?
Did someone else has the same issue??

#### Log Messages
Here are what I can see on my Pihole when the DNS Server on the Homebridge is setup correctly:
query[PTR] 87.178.168.192.in-addr.arpa from 192.168.178.71
query[PTR] 150.178.168.192.in-addr.arpa from 192.168.178.71
query[PTR] 161.178.168.192.in-addr.arpa from 192.168.178.71
query[PTR] 184.178.168.192.in-addr.arpa from 192.168.178.71
see list of different external IPs is very long, that's only an example overview

Here are what I can see on my Homebridge when the DNS Server on the Homebridge is setup incorrectly:
27.11.2020, 12:07:03 [Sonos] error: Command failed: arp -a
27.11.2020, 12:07:03 [Sonos] error: Command failed: arp -a
27.11.2020, 12:07:03 [Sonos] error: Command failed: arp -a
Parallel to this the "query PTR" log entries on the Pihole disappears

**Comment by ebaauw** [comment]
> After some investigation I found out that the ZP Sonos Plugin is creating this DNS request.

Are you sure you're running Homebridge ZP.  Please capture and attach a full debug log, see https://github.com/ebaauw/homebridge-zp#debug-log-file

> [Sonos] error: Command failed: arp -a

That's not a message from Homebridge ZP.  I'm not aware that any of the underlying libraries would do an `arp`.

**Comment by nbunbu** [comment]
As per my Plugin Overview from Homebridge (Hoobs) you can see:

Zp
HOOBS Certified
1.1.1 issued 11/24/2020 • 2 days ago

Plugin for Homebridge homebridge-zp
Copyright © 2016-2020 Erik Baauw. All rights reserved.


via that way I came to your contact deatails here in Github

**Comment by nbunbu** [comment]
I will try to get the Debug Log quickly available

What I can test parallel, that I deinstall the ZP Plugin, change the DNS Server Setting to the correct DNS Server IP and verify what is going on within the Pihole Logfile.
If this "query PTR" enties disappear with this setup it should be something from my Sonos via the ZP Plugin what is creating this issue
Anyway, many thanks for quick response

**Comment by ebaauw** [comment]
Sorry, please contact HOOBS support, see https://github.com/ebaauw/homebridge-zp/issues/136.  I have no idea what they've done to Homebridge nor to my plugins.
