### ISSUE TITLE
apple home app : sonos devices (fan) automatically switching on/off

### ISSUE THREAD

**Issue by pingou100** [ebaauw/homebridge-zp#156]
hi - pretty new with homebridge, GitHub and homebridge-ZP... I succeeded in exposing my sonos players into the apple home app. config.jdon file seems correct : 

    "name": "Sonos",
            "brightness": true,
            "service": "fan",
            "speakers": false,
            "platform": "ZP"

however, when using home app and clicking on the (fan...) icons, it automatically toggles on and off. i tried to change the parameters (switch, lightbulb,...) to check if it would affect this behavior without success. Home app automatically switches off Sonos after 1 second. I don't have errors in the homebridge log (see below)

kitchen Sonos : on changed from false to true
kitchen sonos : set on from true to false

Any idea on how to have the home app toggle button working as per expectation ?

thanks

**Comment by ebaauw** [comment]
The Sonos zone player cannot play when it has no input source.  The Sonos app disables the Play button in that case, but I cannot do that in HomeKit.

**Comment by pingou100** [comment]
user error :-). I had no input source indeed. Thank you Erik, great plugin
