### ISSUE TITLE
Request: Disable unneeded View TV Settings option in TV Accessory

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-zp#158]
Hi Eric

As ever, a great plugin and working really well.

I think you should hide the "View TV Settings" menu option in the TV accessory, as it does nothing. You can hide it with Characteristic.PowerModeSelection.HIDE on the Television accessory.

Don't ask me why Apple named that menu option "PowerModeSelection". It appears to be historical...

**Comment by ebaauw** [comment]
As I mentioned on discord, it's used to set the _Sonos Coordinator_.
