### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by BK234** [ebaauw/homebridge-zp#161]
Would you have any suggestions of how to fix a warning message I am getting every few seconds:

**Comment by ebaauw** [comment]
The message means that the scheduled heartbeat fires 0.3 to 0.4 seconds late.  That could indicate an overloaded system (not the case, looking at the CPU and memory usage) or something blocking NodeJS, most likely another plugin doing synchronous I/O.

Did you try restarting Homebridge?  Have you seen these messages for all 14 days that Homebridge has been running, or did they appear more recently?

**Comment by BK234** [comment]
I restarted Homebridge and the warning is gone.  Thank you!
