### ISSUE TITLE
Devices revert to default room after reboot

### ISSUE THREAD

**Issue by mikeleijs** [ebaauw/homebridge-zp#164]
Can someone help me? Every time my raspberry/homebridge restarts all my sonos speakers are loaded back in the default room. All other accessories from other plugins stay where i’ve put them, only the sonos zoneplay speakers revert back to default room (and my automations lose the speaker settings too).

**Comment by ebaauw** [comment]
How do you restart Homebridge?  What other plugins are you using?

Homebridge ZP is a dynamic platform plugin, that persists the accessories in the user directory under `accessories/cachedAccessories`.  If that file is lost or corrupted, Homebridge will start its HAP server without exposing the Homebridge ZP accessories, causing HomeKit to remove them.  When Homebridge ZP has discovered the zone players and (again) exposes the accessories, HomeKit will treat them as new.

**Comment by mikeleijs** [comment]
Restart through the homebridge-config-ui. Other plugins i use are tahoma, lg webos tv, ics-1000 and tado ac. Maybe the cached file gets lost or corrupt. Is there any way to double check it? Or should i do something to make your plugin save the players to the cached accessories? Thanks in advance

**Comment by ebaauw** [comment]
`cachedAccessories` should be saved automatically.  Please capture a debug log file restarting Homebridge and attach that.

**Comment by mikeleijs** [comment]
I hope this will help.

[homebridge.log.txt](https://github.com/ebaauw/homebridge-zp/files/5984513/homebridge.log.txt)

**Comment by mikeleijs** [comment]
[homebridge.log.gz](https://github.com/ebaauw/homebridge-zp/files/5984518/homebridge.log.gz)

**Comment by mikeleijs** [comment]
here is my cachedAccessories file, don't know if that's needed, but the more info the better I guess. 
[cachedAccessories.zip](https://github.com/ebaauw/homebridge-zp/files/5984530/cachedAccessories.zip)

**Comment by ebaauw** [comment]
Looks like it's not happening on evert restart, but sometimes Homebridge doesn't seem to shutdown cleanly.

You should be seeing the following messages on a clean shutdown:
```
[15/02/2021, 22:53:58] Got SIGTERM, shutting down Homebridge...
[15/02/2021, 22:53:59] [Sonos] closed http://192.168.178.52:36007/notify
[15/02/2021, 22:54:03] [Sonos] goodbye
```
And on startup:
```
[15/02/2021, 22:54:34] [Sonos] restored 3 accessories from cache
[15/02/2021, 22:54:34] [Sonos] restored 1 accessories from cache
```

However, sometimes the `goodbye` message is missing, indicating that NodeJS was stopped before Homebridge ZP did its cleanup.  I've only ever seen this when other plugins would break Homebridge's shutdown sequence, by installing their own handler for SIGTERM.

**Comment by ebaauw** [comment]
> here is my cachedAccessories file, don't know if that's needed, but the more info the better I guess.

Looks like Homebridge ZP is the only plugin using that.

**Comment by mikeleijs** [comment]
Hmm okay, is there any way for me to correct this?

**Comment by ebaauw** [comment]
Run Homebridge ZP as only plugin and check that the issue no longer occurs.  Then re-enable the other plugins one by one to see when the issue re-occurs.  Run the offending plugin in a separate Homebridge instance.  Alternatively, run Homebridge ZP in a separate Homebridge instance, or in a child bridge (new feature in the latest Homebridge beta).

**Comment by mikeleijs** [comment]
I will put homebridge zp in a child bridge instead when homebridge is out of beta. Looks like the easiest way. Thanks.
