### ISSUE TITLE
Request- Volume limit

### ISSUE THREAD

**Issue by mbeck94** [ebaauw/homebridge-zp#17]
Request for a way to limit the maximum volume or a way to not have the volume go to 100 when turning on. Using the 'light' Service.

**Comment by ebaauw** [comment]
How are you turning on the Sonos?  I use a HomeKit scene that sets the both the `On` and `Volume` characteristics and  I've never run into issues that the Sonos starts playing too loudly.  I did run into some funny behaviour with _Autoplay Volume_ on the _Line-In_, so I disabled that in _Room Settings_ in the Sonos app.

I could introduce a config.json parameter `maxVolume` and use that to set the `maxValue` property of the characteristic used for volume (be that `Volume`, `Brightness`, or `RotationSpeed`).  With this you wouldn't be able to set volume above `maxVolume` from HomeKit, but you would still be able to do that from the Sonos app, or from the physical buttons on the speaker.

Alternatively, I could introduce a config.json parameter `poweronVolume`, and set the zone volume to this level, just before issuing the _Play_ command.  However, this could break my HomeKit scene, if it sends the change to `Volume` before the change to `On` (I don't think there's a way to force the order in which HomeKit handles the characteristics in a scene).  Also, this would reset the volume after each Pause/Play.

**Comment by mbeck94** [comment]
Hm, I haven't had the issue since posting this. I believe it was related to the fact the when the Sonos is first added and turned on, its default was to play at 100, however, once adjusting and turning off and back on, the volume reverts back to its last state. It seemed like a bigger issue to me at the time since I had added and removed homebridge from my Home multiple times while tweaking it, resulting it it always turning on to 100. 

Thanks for your awesome work on this! It's a really great addition to Homebridge! 
This issue can be closed.

**Comment by Jeff1741** [comment]
I would like to request that this feature be implemented. My Sonos is on my desk and I usually have it <10% volume (loud enough for when I'm studying or something), and having the max be 100% has lead to be accidentally blasting music. A maxVolume config parameter would be great, and also a poweronVolume one too, so I can change volume, THEN play my music.

Thanks!
