### ISSUE TITLE
Sonos Roam

### ISSUE THREAD

**Issue by Marcus235** [ebaauw/homebridge-zp#175]
#### Issue

Sonos Roam support

Will this be added? Thanks

#### Log Messages

```
```

**Comment by ebaauw** [comment]
What support do you mean?  What is not working?

**Comment by Marcus235** [comment]
Hallo,

Volgens mij wordt de Roam niet herkend. Hij staat ook niet in de lijst, wellicht omdat deze vrij nieuw is. Ik zie met de laatste update de Roam er niet tussen staan? 

Met vriendelijke groet, kind regards,

Marcus Bitterling

**Comment by ebaauw** [comment]
Please the conversation here in English, so others can benefit from it.

What list?  I don't have a Roam myself, but seen reports that it works.  I even added support for the battery in the latest version, see #172.

**Comment by Marcus235** [comment]
It seems there was something wrong on my end. After several restarts it appeared. 
This is the list I refer too. Same on Github site. The Roam is not mentioned so I was under the impression it was not supported. 


Met vriendelijke groet, kind regards,

Marcus Bitterling

**Comment by ebaauw** [comment]
Make sure it's on Wifi.  When it appears in the Sonos app, it should also appear in Homebridge ZP.
