### ISSUE TITLE
Airplay Support

### ISSUE THREAD

**Issue by adavison007** [ebaauw/homebridge-zp#178]
Hi, I know this is a repetitive conversation, but it would be a cool feature if you could enable this, I know in the past I've been advised it is not possible. However, see attached of what Starling have done for google devices to use airplay via their home bridge plugin in, is this possible via yours for Sonos? Big thanks in advance and love your plugin.
<img width="719" alt="Screenshot 2021-06-14 at 09 55 20" src="https://user-images.githubusercontent.com/47482260/121866587-f89d1f80-ccf6-11eb-9287-fcba3f508e16.png">

**Comment by ebaauw** [comment]
Yeah, it would be cool.  No, it's not happening - see the other issues.
