### ISSUE TITLE
Repo Name

### ISSUE THREAD

**Issue by mefynn** [ebaauw/homebridge-zp#18]
Your plugin is **far** better than homebridge-sonos... 
you might wanna change your repos name to something, that can actually be found. ✌🏻

cheers.

**Comment by ebaauw** [comment]
Thanks!

The name needs to be unique in npm, so, unfortunately, I cannot re-use homebridge-sonos.

How are you trying/hoping to find it?  I set keywords `homebridge-plugin`, `sonos`, and `zoneplayer`, but I'm more than happy to set some more to increase visibility.

**Comment by mefynn** [comment]
Sounds good! 
I would go with something like »homebridge-sonos-zp« (if double hyphen is allowed).
I found your plugin through your homebridge-hue plugin and immediately shared it with all the folks in the homebridge slack-channel...

thanks for all your work. 
I'm gonna close this issue
