### ISSUE TITLE
initTopology() not yet called - new symptom

### ISSUE THREAD

**Issue by JeffGoldner** [ebaauw/homebridge-zp#182]
#### Issue

Recent error message, initTopology()

#### Log Messages

[8/16/2021, 11:33:50 AM] [Sonos] error: SyntaxError: initTopology() not yet called
    at ZpClient.checkInitTopology (/homebridge/node_modules/homebridge-zp/lib/ZpClient.js:527:13)
    at ZpClient.get bootSeq [as bootSeq] (/homebridge/node_modules/homebridge-zp/lib/ZpClient.js:593:10)
    at ZpPlatform.heartbeat (/homebridge/node_modules/homebridge-zp/lib/ZpPlatform.js:150:40)
    at ZpPlatform.emit (events.js:400:28)
    at ZpPlatform.emit (/homebridge/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Delegate.js:174:13)
    at ZpPlatform._heartbeat (/homebridge/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:303:10)
    at ZpPlatform._beat (/homebridge/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:291:42)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-zp/node_modules/homebridge-lib/lib/Platform.js:281:12)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by ebaauw** [comment]
Please capture and attach a debug log file.

New symptom since when, since what change?  Does the message appear shortly after starting Homebridge or after a longer time?  Did you power-on or reboot a zone player just before the message appeared?

I don't think this is impacting any functionality?  I suppose the message could appear when a new zone player is discovered and still being probed, when the timer to check whether the zone player is still online fires (once every five minutes).

**Comment by adavison007** [comment]
I have the same issue since the last update... reverting to the previous version does not resolve....

<img width="1190" alt="Screenshot 2021-08-22 at 21 13 20" src="https://user-images.githubusercontent.com/47482260/130368797-f4b59d2d-5e3a-43a3-9660-07491fb7f5a4.png">

**Comment by adavison007** [comment]
Just updated node too to try to resolve and am getting this issue...

<img width="1181" alt="Screenshot 2021-08-22 at 21 26 20" src="https://user-images.githubusercontent.com/47482260/130369116-7f016daf-f39a-4d19-acd1-2e161597d30e.png">

**Comment by adavison007** [comment]
I removed the plugin and reinstalled, 'i don't see  how to add the speakers again, how doi clean the cache without removing all the accessories from other plugins

**Comment by adavison007** [comment]
> I removed the plugin and reinstalled, 'i don't see how to add the speakers again, how doi clean the cache without removing all the accessories from other plugins

@ebaauw OK, found how to delete the previous speakers in the homebridge settings... reinstall of your app and re adding speakers worked fine!

**Comment by ebaauw** [comment]
I still have the same questions as [before](https://github.com/ebaauw/homebridge-zp/issues/182#issuecomment-899767207).  Without those answers, I cannot analyse what’s happening.

**Comment by adavison007** [comment]
@ebaauw Sorry for missing your question. The speakers in homekit became "Unresponsive" and could not longer be used. The switches were able to be used. This is why I had to delete all and start again. The switches remained functional. I still do not understand why I have a switch and a speaker tile... why not just speaker, or is this a miss understanding of the setup?

**Comment by ebaauw** [comment]
> The speakers in homekit became "Unresponsive" and could no longer be used. The switches were able to be used. This is why I had to delete all and start again. 

I don't think it is, actually.  Nine out of ten times, accessories showing _No Response_ are caused by a failed network connection between your iDevice and the accessory.  This is usually resolved by switching off and back on WiFi on your iPhone or iPad.  Note that the switches are bridged whereas the speakers are standalone accessories, that need to be paired to HomeKit individually.

> why not just speaker,

The speakers only show in Home, not in other HomeKit apps.  And Home doesn't support all of HomeKit, so you want to use Eve or another HomeKit to use the full features of Homebridge ZP (and many other Homebridge plugins).

**Comment by adavison007** [comment]
@ebaauw Thanks for the update. I am not technical, just to confirm, the issues occurred after I rebooted home bridge following the update of your plugin. The speakers showed as non responsive in my home app on my mac book (wifi), my iMac (wired ethernet) and also my iPhone (wifi). Hope this helps.

**Comment by ebaauw** [comment]
I really need a debug logfile, from starting Homebridge, leading up to the error.

**Comment by JeffGoldner** [comment]
[homebridge.log.txt](https://github.com/ebaauw/homebridge-zp/files/7041086/homebridge.log.txt)

Hope this helps. I updated node this AM, then your latest plug-in version, then restarted the docker container.

**Comment by ebaauw** [comment]
Yeah, I think this got the info I need, thanks.  It definitely has some fun ingredients: a Sonos Boost, several zone players with a new IP address.  I need to see if I can re-construct what happened.  There's actually another error in your log as well.

@JeffGoldner do you also have a Boost?

**Comment by adavison007** [comment]
@ebaauw No boost for me... I would send a log, but have no idea how to get it for you  and how long it saves the info for?

**Comment by JeffGoldner** [comment]
> Yeah, I think this got the info I need, thanks. It definitely has some fun ingredients: a Sonos Boost, several zone players with a new IP address. I need to see if I can re-construct what happened. There's actually another error in your log as well.
> 
> @JeffGoldner do you also have a Boost, by chance?

Yes, I do have a Boost. I also have one Play:5 second gen in the garage that has native Airplay 2, since it looks like that one might be an issue? All the other Sonoses are not Airplay.

**Comment by ebaauw** [comment]
I do have some zone players with native Airplay2, they should work fine.  I don’t have a Boost, though, and it did cause some unexpected (by me, at least) issues in the past.

**Comment by adavison007** [comment]
@ebaauw I've just rebooted my homebridge and the speakers are no longer responsive again... before I remove and re add again, did you want me to get a log, if so how do I do this?

**Comment by ebaauw** [comment]
Could you check with the Discovery app (on iOS or macOS, see http://www.tildesoft.com), if the TV accessories are advertising themselves over Bonjour?  The should appear under `_hap._tcp`, next to the Homebridge bridge accessory.

Are you using Docker?  Make sure the `persist` directory is indeed persisted between reboots.

**Comment by adavison007** [comment]
I run homebrige on PI, no docker. I run sonos zp as a child bridge, see screen shots.... let me know what to do next? I've click add new accessory and they do not show... 

<img width="708" alt="Screenshot 2021-08-24 at 20 42 03" src="https://user-images.githubusercontent.com/47482260/130679676-0845be51-5720-4ae6-98a4-fcaa064e6388.png">
<img width="708" alt="Screenshot 2021-08-24 at 20 42 36" src="https://user-images.githubusercontent.com/47482260/130679687-89bc7e94-4792-4fe3-9367-fbdaa833b93e.png">

**Comment by ebaauw** [comment]
So the advertisement looks OK, and Homebridge thinks the accessory has been paired with HomeKit. Is the suffix, CAFB, the same as when you originally paired it?  You could check with `netstat` on the Pi that there are incoming connections to port 39819 or at least that Homebridge is listening on that port.

If you disable/re-enable WiFi on your iPhone, does the speaker become responsive?  And if you reboot the iPhone?

**Comment by adavison007** [comment]
> I think that is the advertisement for the child bridge? I don't see any for the TV accessories? Did you see messages in the log that the external accessories were started, and you needed to pair them manually?

No, didn't see anything, sorry.  I am now deleting the plugin, deleting the child bridge and starting again

**Comment by adavison007** [comment]
So after reinstall they appear.... Bedroom, Patio, BBQ etc etc


<img width="620" alt="Screenshot 2021-08-24 at 22 03 18" src="https://user-images.githubusercontent.com/47482260/130689608-095392b8-b3ab-4cc5-9372-e3ea3233a02e.png">

**Comment by adavison007** [comment]
@ebaauw and they still work after a reboot :)

**Comment by ebaauw** [comment]
After running for a day I saw no weird side-effects, so I published a regular release.  That should handle the changing IP addresses.

**Comment by JeffGoldner** [comment]
@ebaauw I update the plugin just now and no longer see the reported problem. The Boost is showing up in the log as seen - not that there is much to do with it.
Closing the issue! Many thanks.
