### ISSUE TITLE
Can't join/group two Sonos speakers with command line : zp join

### ISSUE THREAD

**Issue by pzim-devdata** [ebaauw/homebridge-zp#186]
#### Issue

Hello,

Thank you so much for your homebridge plugin.

I have a problem when I want to group my Sonos Roam and my Sonos One to play together.
When I use this command line to join : ```zp -H 192.168.1.107 join RINCON_542A1B452AEC01400``` I have the following error message : 

``` 
    zp join: error: SyntaxError: initTopology() not yet called
    at ZpClient.checkInitTopology (/usr/local/lib/node_modules/homebridge-zp/lib/ZpClient.js:527:13)
    at ZpClient.get zones [as zones] (/usr/local/lib/node_modules/homebridge-zp/lib/ZpClient.js:944:10)
    at Main.join (/usr/local/lib/node_modules/homebridge-zp/cli/zp.js:1067:36)
    at Main.main (/usr/local/lib/node_modules/homebridge-zp/cli/zp.js:691:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Could you help me please ?

#### Log Messages
Here is the result of ```zp -H 192.168.1.107 topology``` : 
```
zp topology: listening on http://0.0.0.0:42525/notify
{
  "RINCON_48A6B8F17EB401400": {
    "address": "192.168.1.107",
    "airPlay": true,
    "bootSeq": 2,
    "household": "Sonos_4E7jmaGsILCFp4B0pHewJ9Oowz",
    "id": "RINCON_48A6B8F17EB401400",
    "name": "Salle à manger",
    "role": "master",
    "zone": "RINCON_48A6B8F17EB401400",
    "zoneDisplayName": "Salle à manger",
    "zoneGroup": "RINCON_48A6B8F17EB401400",
    "zoneGroupName": "Salle à manger",
    "zoneGroupShortName": "Salle à manger",
    "zoneName": "Salle à manger"
  },
  "RINCON_542A1B452AEC01400": {
    "address": "192.168.1.128",
    "airPlay": true,
    "battery": {
      "rawPercentage": 98,
      "percentage": 100,
      "charging": true,
      "temperature": 24
    },
    "bootSeq": 82,
    "household": "Sonos_4E7jmaGsILCFp4B0pHewJ9Oowz",
    "id": "RINCON_542A1B452AEC01400",
    "name": "Salon",
    "role": "master",
    "zone": "RINCON_542A1B452AEC01400",
    "zoneDisplayName": "Salon",
    "zoneGroup": "RINCON_542A1B452AEC01400",
    "zoneGroupName": "Salon",
    "zoneGroupShortName": "Salon",
    "zoneName": "Salon"
  }
}

```

**Comment by ebaauw** [comment]
That smells like a bug in `zp`.  I haven’t tried `zo join` for a long time, and messed with the initialisation order several times to address issues in Homebridge ZP.  I need to do some testing this weekend to analyse what went wrong.

**Comment by pzim-devdata** [comment]
> That smells like a bug in `zp`. I haven’t tried `zo join` for a long time, and messed with the initialisation order several times to address issues in Homebridge ZP. I need to do some testing this weekend to analyse what went wrong.

Thanks ;-)

**Comment by ebaauw** [comment]
That was simple, just call `initTopology()`.  Also fixed some debug messages while at it.

**Comment by ebaauw** [comment]
In v1.4.9.

**Comment by pzim-devdata** [comment]
Thank you for your answer. 
Could you explain to me how to call ``initTopology()``` ?

**Comment by ebaauw** [comment]
I don’t know the RINCON numbers of my zone players by heart, so It makes more sense to me to use the zone name, instead of the zone player ID.  I did consider using the hostname or IP address (to be consistent with the `-H` flag), but that would be more complex technically and I never implemented that.

**Comment by pzim-devdata** [comment]
Yes you're right. It's perfect like this. I meant in zp help when we execute ``` zp -h```, the ``join`` line should be ```join [-h] zoneGroupName``` or ``` join [-h] zoneDisplayName ``` and not ``` join [-h] zone```
Thank you for your help ;-)
