### ISSUE TITLE
Support for Sonos Alarms

### ISSUE THREAD

**Issue by alexlewer** [ebaauw/homebridge-zp#19]
Hi @ebaauw,

Would there be any scope to surface a HomeKit switch to enable/disable an "alarm" (in Sonos terminology) that had been set via the Sonos app? I would ideally like to be able to enable/disable my alarms via a HomeKit automation.

Thanks!
Alex

P.S - awesome work on both this, and [homebridge-hue](https://github.com/ebaauw/homebridge-hue). Both working like a dream, including the new programmable switch fixes in [0.3.15](https://github.com/ebaauw/homebridge-hue/releases/tag/v0.3.15).

**Comment by ebaauw** [comment]
Interesting suggestion!  I use schedules on my Hue bridge for my alarms and then switch on the Sonos through HomeKit automation.  I suppose the reverse route makes just as much sense: use Sonos alarms and then switch on the lights using HomeKit automation.

I could probably add a service per alarm, with a custom `Enabled` attribute, to each Sonos accessory, similar to the support of schedules in homebridge-hue.

**Comment by alexlewer** [comment]
Sounds good! My actual use-case for this is to use [homebridge-people](https://github.com/PeteLawrence/homebridge-people) to enable/disable the Sonos alarm (if someone is home, enable my weekday alarm, if not, disable it).

**Comment by ebaauw** [comment]
Sorry for coming back on this so late; I've been very busy with homebridge-hue and deCONZ.

v0.2.10 supports enabling/disabling Sonos alarms from HomeKit.  When setting `"alarms": true` in config.json, homebridge-zp exposes an additional (custom) service for each alarm, in the corresponding zone (room) accessory.  These services contain a (custom) characteristic `Enabled` to enabled/disable the alarm.

Note that homebridge-zp only loads alarms on startup.  When you create, change or delete alarms, homebridge must be restarted before homebridge-zp reflect the changes.

Note that the service is named after the alarm time and track when it's first created, but this name cannot be updated from HAP.  To refresh the names, set `"alarms": false` in config.json and restart homebridge (so HomeKit deletes the services).  Then set`"alarms": true` and restart homebridge once again.
