### ISSUE TITLE
Allow settings-only mode

### ISSUE THREAD

**Issue by SamTheGeek** [ebaauw/homebridge-zp#198]
There should be a way to only show settings (and even user-defined lists of settings) in HomeKit as a multi-switch accessory. 

This would allow voice control of settings such as speech enhancement or night mode without requiring any other visibility of Sonos in HK. 

Ideally, I would be able to configure SonosZP to show a single tile that allowed me to turn on or off Night Mode and Speech Enhancement and any subwoofer I had paired to a given zone/surround setup. This would allow me to automate the "evening" Sonos settings along with lights and other HK devices.

**Comment by ebaauw** [comment]
You can change the settings from Siri: use Eve or another decent HomeKit app to create a scene with the setting.  Then recall that scene from Siri.

Only exposing a single setting is beyond the scope of Homebridge ZP.  If you don’t like to see the accessories exposed by Homebridge ZP, don’t use that plugin.  You could probably use a plugin like homebridge-commander to expose dummy switches that issue `zp` commands to change a setting.
