### ISSUE TITLE
Warning errors

### ISSUE THREAD

**Issue by RadDip** [ebaauw/homebridge-zp#199]
#### Issue
Zp Bridge 2SonosWARNINGwarning: heartbeat 160622, drift 3947
10/16/2022, 8:07:05 AMZp Bridge 2SonosWARNINGwarning: heartbeat 160623, drift 3182
10/16/2022, 8:07:05 AMZp Bridge 2SonosWARNINGwarning: heartbeat 160624, drift 2187
10/16/2022, 8:07:05 AMZp Bridge 2SonosWARNINGwarning: heartbeat 160625, drift 1189

#### Log Messages

```
Zp Bridge 2SonosWARNINGwarning: heartbeat 160622, drift 3947
10/16/2022, 8:07:05 AMZp Bridge 2SonosWARNINGwarning: heartbeat 160623, drift 3182
10/16/2022, 8:07:05 AMZp Bridge 2SonosWARNINGwarning: heartbeat 160624, drift 2187
10/16/2022, 8:07:05 AMZp Bridge 2SonosWARNINGwarning: heartbeat 160625, drift 1189
```

#### Debug Files
Running Hoobs Box version 4.2.8 
Homebridge version 1.5.0
Node version 16.17.1

**Comment by ebaauw** [comment]
A scheduled heartbeat happened 4s late.  If this happens structurally, it might be an indication that some other plugin is doing synchronous I/O, blocking NodeJS, or that the server running Homebridge might not be powerful enough.
