### ISSUE TITLE
Setting sleep timer causes the current track to pause

### ISSUE THREAD

**Issue by sreknob** [ebaauw/homebridge-zp#20]
I've been trying to figure this out for a while and just realized that it's homebridge-zp causing the problem when I tailed the log. With music playing when I select a sleep timer the track pauses and needs to be restarted. Log looks like this:
[ZP] Office Sonos: current track changed from Yellow Submarine to The Curse Of Comfort
[ZP] Office Sonos: power (play/pause) changed from true to undefined
[ZP] Office Sonos: set power (play/pause) from undefined to false
[ZP] Office Sonos: current track changed from The Curse Of Comfort to undefined
[ZP] Office Sonos: power (play/pause) changed from undefined to false
[ZP] Office Sonos: current track changed from undefined to The Curse Of Comfort
This happens every time I select a sleep timer duration or change the duration.
Thanks for looking into this!

**Comment by ebaauw** [comment]
Thanks for noticing this!  I found the same behaviour recently, but hadn't linked it to homebridge-zp.  I did change the logic regarding power (play/pause), see https://github.com/ebaauw/homebridge-zp/issues/12#issuecomment-298567685, maybe introducing this behaviour.  I'll definitely have a look.

**Comment by ebaauw** [comment]
Yup, this is a bug introduced in v0.2.1.  Solved in v0.2.3, which I just published.

**Comment by sreknob** [comment]
Amazing, many thanks!
Just updated and issue resolved.
Don't tell Sonos support (whom I've been bugging for a month) that this was the issue. LOL
