### ISSUE TITLE
Homebridge -zp

### ISSUE THREAD

**Issue by MarkP63** [ebaauw/homebridge-zp#201]
#### Issue

Sonos icon appears under HB accessories and from there turns on/off Sonos
Home App shows “Sonos Beam” Orange House icon but says not supported? - And has not functions
Another greyed out Beam button appears in the same room and says not playing (when it is). Opening
This greyed icon shows greyed out play and FFWD/RWD arrows but again do not function.
All other Sonos products in other rooms have been identified in the same way but zero functionality. 

I have just used as is and not modified the Config.json ?  Do I need to add/modify this from the standard one?
Node.js Version. = 18.12.1

I have upgraded to 16.2 and new Home architecture but it didnt work before that so gave up. 

Thanks for any guidance

#### Log Messages

```
```

**Comment by ebaauw** [comment]
> Sonos icon appears under HB accessories and from there turns on/off Sonos

I've never seen a Sonos icon in HomeKit.  Do you mean a speaker icon?  Is this the Airplay 2 icon provided by the Sonos speaker itself?

> Home App shows “Sonos Beam” Orange House icon but says not supported?

Did you check another HomeKit app?  What's the config.json setting for `service`?  Please check the READ_ME before setting this to "speaker".

**Comment by ebaauw** [comment]
You need to read the README:

> Selecting `"speaker"` results in a _not supported_ accessory in Apple's Home app.

**Comment by MarkP63** [comment]
Thanks, Whilst fairly IT literate (ran a small business for 25 years) I am not a programmer and JSON has passed me by…

I have tried to Read the README but I am not understanding because its written as it you know this stuff, sorry I’m a novice. I have successfully integrated many other eco systems but often just need a pointer not an assumption I know the syntax of Json. 

 

So what should it be set to? The install sets speaker to “true” ?

 

Also do I need the rest of your config.schema.json? embedded….

 

Thanks

 

Mark

 

From: Erik Baauw ***@***.***>
Reply to: ebaauw/homebridge-zp ***@***.***>
Date: Wednesday, 21 December 2022 at 17:45
To: ebaauw/homebridge-zp ***@***.***>
Cc: Hide My Email ***@***.***>
Subject: Re: [ebaauw/homebridge-zp] Homebridge -zp (Issue #201)

 

You need to read the README:

Selecting "speaker" results in a not supported accessory in Apple's Home app.

**Comment by ebaauw** [comment]
> just need a pointer not an assumption I know the syntax of Json.

https://www.json.org/json-en.html

But it's probably easier to use the Homerbidge UI.
