### ISSUE TITLE
Ghost Sonos speakers appearing - advise please

### ISSUE THREAD

**Issue by eranhuman** [ebaauw/homebridge-zp#205]
#### Issue

Hi there. So I recently gave away 3 older Sonos speakers.
They disappeared from my Sonos System (when logging into my account online) after they were activated by the friends I gave them to. So In the Sonos app and online in my Sonos account those speakers are gone.

HOWEVER in the hoops plugin they still appear. I have even uninstalled and reinstalled the plugin.

Hoping for some guidance (or) for the ability to tell it to ignore certain speakers.

Appreciate any feedback you can give me.

#### Log Messages

```
```

**Comment by ebaauw** [comment]
Try power-cycling all your zone players and after that restarting Homebridge.

**Comment by eranhuman** [comment]
To clarify, I should turn them all off and then turn them all back on or power cycle of them one at a time?Sent from my iPhoneOn May 5, 2023, at 5:30 PM, Erik Baauw ***@***.***> wrote:﻿
Try power-cycling all your zone players and after that restarting Homebridge.

**Comment by ebaauw** [comment]
Shouldn’t matter.

**Comment by eranhuman** [comment]
I basically killed the power to all of the rooms waited five minutes and turned all the power back onThis also rebooted the Home bridgeNo change the legacy three speakers are still there? :(Sent from my iPhoneOn May 5, 2023, at 5:50 PM, Erik Baauw ***@***.***> wrote:﻿
Shouldn’t matter.

**Comment by eranhuman** [comment]
Any thoughts?

**Comment by ebaauw** [comment]
> I have even uninstalled and reinstalled the plugin.

Did you start Homebridge without the plugin installed?  If not, the ghost zone players might be left behind in `cachedAccessories`.

**Comment by ebaauw** [comment]
Beware that if you do that, all your HomeKit ZP accessories with be reset, losing any associations to HomeKit rooms, groups, scenes, and automations.  The Homebridge UI allows you to remove individual accessories from `cachedAccessories`.

**Comment by eranhuman** [comment]
Any chance you can send me a link wit a little more info on how to do that - thats what I have been looking for but haven’t seen anything like that.

Also THANK you so much for your guidance and assistance.

**Comment by ebaauw** [comment]
It's _Manage Cached Accessories_ under _Homebridge Settings_.  You need a standard Homebridge installation managed by the UI to see that option.

**Comment by eranhuman** [comment]
Thanksjust to be clear the whole cache it will rebuild based on what it can find right?Sent from my iPhoneOn May 8, 2023, at 8:35 PM, Erik Baauw ***@***.***> wrote:﻿
It's Manage Cached Accessories under Homebridge Settings.  You need a standard Homebridge installation managed by the UI to see that option.

**Comment by eranhuman** [comment]
This worked! Thank you. Sent from my iPhoneOn May 8, 2023, at 8:35 PM, Erik Baauw ***@***.***> wrote:﻿
It's Manage Cached Accessories under Homebridge Settings.  You need a standard Homebridge installation managed by the UI to see that option.
