### ISSUE TITLE
HomeKit Speaker support in iOS 11

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-zp#21]
Just a placeholder to see if we can make use of HomeKit Speaker support in iOS11.  See also https://github.com/nfarina/homebridge/issues/1326.

**Comment by leoneleone** [comment]
@ebaauw I've got iOS 11 running on my HomeKit setup. Finding that Siri controls initiate and run faster. I'd like to test how Sonos would run as a HomeKit speaker 🙂

**Comment by ebaauw** [comment]
I've yet to see a clue clue how the Airplay 2 speakers will be exposed to HomeKit.  Did you try setting `"service": "speaker"` in config.json?  With that setting homebridge-zp exposes the sonos as a `Speaker` service.

**Comment by leoneleone** [comment]
I’ve already tried that. The Speakers show up with a house icon and “accessory unsupported”. 

I guess haven’t provisioned for Service.Speaker in the first beta - well not for an independent Speaker accessory yet. Unless I’m doing something wrong...

**Comment by xxjs17xx** [comment]
I’m in the same boat. Changing service to speaker renders the devices unsupported in the home app on ios11 beta.

**Comment by leoneleone** [comment]
@ebaauw
Regarding AirPlay 2:
https://developer.apple.com/videos/play/wwdc2017/509/

I'm wondering if we can somehow make the Sonos speakers visible to HomeKit as AirPlay2 speakers but adding the relevant components to your plugin??

**Comment by ebaauw** [comment]
I guess we'll have to wait for iOS 11 and tvOS 11 (the AppleTV v4 would support Airplay 2) to see what Airplay 2 really looks like.  The way I understand it, it's an "upgrade" of the current Airplay protocol, to stream audio (and video) combined with playback control through HomeKit.

The streaming part has nothing to do with HomeKit, and won't be supported through homebridge.  You need something like an Airplay2 version of [airsonos](http://airsonos.stephenwan.net), which, unfortunately, I never got running (I didn't have the time to figure out why).

As for the playback control: I hope for the best, but fear the worst, as to how Apple will implement this.  Will the Airplay2 device expose itself as a HomeKit accessory over HAP?  In this case, we could use the same service(s) and charactertistics for homebridge-zp.  However, when HomeKit uses a shortcut and interacts directly with the Airplay2 device over Airplay2, it might be impossible to duplicate that using homebridge.

**Comment by ebaauw** [comment]
Hmm the airsonos project seems abandoned, but I got it running by following the steps for [Development](https://github.com/stephen/airsonos#development) install and applying patch 1 and 3 from https://github.com/stephen/airsonos/issues/342#issuecomment-295770479.

**Comment by leoneleone** [comment]
The developer video I posted in my comment above details the small changes to the code which enable Airplay 2 functionality. 
I believe you have to enable the Airplay 2 option on your iOS beta phone in the Settings>Developer menu of the iPhone 😊

**Comment by ebaauw** [comment]
Just tried iOS 11 public beta 3: I see no noticeable changes to the `Speaker` service: the iOS builtin Home app still shows it as not supported.

**Comment by xxjs17xx** [comment]
That makes me sad :(

**Comment by leoneleone** [comment]
@ebaauw 
you say you just tested iOS 11 beta 3, Apple just release beta 4 yesterday...
I have the plugin setup to show Switches in HomeKit. I'll find time to change it to the Speaker service and see if it works under beta 4

**Comment by ebaauw** [comment]
Public beta 3, released yesterday as well, which should match developers beta 4.

**Comment by leoneleone** [comment]
@ebaauw
Ah ok. Didn’t realise you meant the public beta. 
I guess we’ll just have to see as the betas progress. 

I have my sonos connected to airplay via an Airport Express (with AirTunes/AirPlay). That’s why I was hoping we could expose the zip speakers as Airplay 2 compatible via the homebridge-zp plugin... but that seems not possible for now. 
It would be great if somehow homebridge-zp could tag or expose each sonos room/zone as Airplay 2 speakers. Wishful thinking perhaps

**Comment by ebaauw** [comment]
Nothing wrong with a bit of wishful thinking...  I don't know about Airplay 2, but I think it would be possible to integrate airsonos in homebridge-zp.  I won't be looking into that until I'll have refactored the code to support dynamic platform accessories, though.

I fear Airplay 2, while part of the HomeKit API, won't be part of HAP, so there's nothing homebridge could do.  Of course, it would be possible to integrate the Sonos side of homebridge-zp into airsonos, but I have no idea whether airsonos could be enhanced to support Airplay 2.

**Comment by leoneleone** [comment]
@ebaauw 

Might be a wait and see situation regarding airsonos airplay2.

I have in the meantime been able to get AirPlay2 output from my AppleTV (running the latest tvOS beta) into my Sonos by connecting the AppleTV gen4 directly to my Sonos Connect (bridge): either using an HMDI to rca audio converter, or by Airplying the AppleTV audio output to my (Sonos 'Connect'ed) Airport Express. Of course this feeds into my overall Sonos system and multi-room control is still done via the Sonos app or homebrige-zp using this method. In theory one could use multiple Sonos Connects/Apple Tvs/AirportExpresses to achieve a kind of "zoning"/clustering of Sonos Plays into rooms or groups with separate "Line-in" inputs, but the cost of such an endeavour doesn't seem reasonable. It is, however, a possible - yet expensive- solution for achieving multi-"zone" Airplay2 support with a home Sonos system.
The only problem I've encountered so far has been volume control from my source device (iPhone running iOS 11 beta): It seems the iPhone volume control becomes redundant and does not effect the Airplay 2 music stream while using Airplay 2, it only controls the iOS device volume and not the Airplay 2 audio stream.  This will definitely get fixed or changed in upcoming iOS 11 betas. Apple have said multi-room AirPlay 2 support will be coming in future betas...

I have to say though, being able to Airplay (2) music from my iPhone and still be able to make/take phone calls, use Siri from my iPhone, and play videos on my phone - without the airplay music stream to Sonos being cut off - is really a wonderful experience. It just feels right 🙂 

I'm not a Sonos app user really, and find Airplay a much easier solution for me at home.

If in the future airsonos is updated with Airplay2 functionality and you can somehow integrate airsonos in to homebridge-zp, that would be amazing! I'll keep my fingers crossed.

**Comment by ebaauw** [comment]
> The only problem I've encountered so far has been volume control from my source device (iPhone running iOS 11 beta)

Does the current iOS 11 beta already show the AirPlay2 enabled AppleTV in Home?  The "screenshot" during the keynote seemed to indicate that you'd get volume control in the Home app.

> I have in the meantime been able to get AirPlay2 output from my AppleTV (running the latest tvOS beta) into my Sonos by connecting the AppleTV gen4 directly to my Sonos Connect (bridge): either using an HMDI to rca audio converter, or by Airplying the AppleTV audio output to my (Sonos 'Connect'ed) Airport Express.

I have a Sonos Connect hooked up to my mac server, and use [Airfoil](https://rogueamoeba.com/airfoil/) to make the server present itself as AirPlay speaker.  I use the Connect as my primary zone, grouping/ungrouping the other zones (rooms) using homebridge-zp as I enter or leave the room (as detected using the Hue motion sensor).  
I also have my TV hooked up to the Sosos PlayBar (over TOSlink), and the AppleTV to the TV (over HDMI), so I can also Airplay to the AppleTV, but my TV needs to be switched on for this to work.

With the Sonos feature to auto switch to LineIn (or optical in) when it detects input, it's an almost seamless experience, except for switching back to the previous music source (typically Internet radio).  It's on my todo list to add support for this to homebridge-zp (issue #8).  I still use the Sonos app for that.

As mentioned before, I got airsonos to work.  It creates an AirPlay device and an Internet radio station per Sonos zone.  When an Airplay client connects, it switches the zone's input to the corresponding station, re-broadcasting it's incoming stream.  I think I do a better job at discovering Sonos zones in homebridge-zp (incl. the grouping), so integrating airsonos makes sense to me.  Also the mdns module used by airsonos is already part of homebridge, as both HomeKit and AirPlay depend on Bonjour.

As I mentioned before, airsonos seems to be abandoned, I doubt if it will support AirPlay 2.  Even if it would, you might still prefer to use Sonos for multi-room control.  I doubt that multiple streams from AirPlay 2 into different Sonos zone will result in synchronised audio between the zones.  I know from experience, multiple Internet radio streams don't.

**Comment by leoneleone** [comment]
@ebaauw 
Thanks for all the information. 

If only I had a Soundbar - and if only the Apple TV 4 has an optical out port 😔 

The Apple TV does not show up as a Speaker in the Home.app, probably because it’s identified as an AppleTV rather than a Speaker. Still no multi-room audio control with AirPlay2 in iOS 11 beta 5 (dev) unfortunately.

**Comment by leoneleone** [comment]
@ebaauw 
Just a small update:
Since the last two beta updates, Apple has somehow stopped the AirPlay2 functionality I mentioned a few posts above. The music stream is still technically an AirPlay2 stream, but the music now pauses automatically if I make or take a call on the streaming iOS device. I believe this is a change within iOS 11 beta rather than tvOS 11 beta (my AirPlay bridge, so to speak). I think Apple is still working out the details of how AirPlay2 plays out, if you’ll excuse the pun. Seeing as we won’t see an official AirPlay2 speaker until December (the HomePod), I don’t think we’ll see a final version of AirPlay2 until then. 

The AppleTV still does not show up at a “Speaker” device within the Home.app 😔 

Any chance you’ve a look at the HomePod firmware that found it’s way to developers by mistake? I believe it would shed more light on the HomeKit Speaker functionality we all expect from the HomePod Speaker.
I know that the “HomeKit Speaker” issue is supposedly a purely AirPlay2 function, but I’m still holding out hope that some useful/usable info can be uncovered from the HomePod firmware regarding the topic of this “issue” thread. Maybe there’s something specific there which can be utilised within your plugin?
🤞🏼

**Comment by leoneleone** [comment]
@ebaauw 
Had a new thought today over coffee:
Maybe the way forward would be to expose each Sonos “Zone” or any grouped ZPs/Rooms as a HomePod somehow.
I don’t know it this is possible, just thinking out load. 

Have you had a chance to look at or read about the details of the HomePod firmware I mentioned before?

**Comment by ebaauw** [comment]
Sonos announced Airplay2 support coming next year!

**Comment by leoneleone** [comment]
That’s great!!
My only caution is that Sonos is notoriously slow in releasing new features they announce. I hope we won’t waiting too far into 2018 for an actual release 🙏🏼✝️

**Comment by alexlewer** [comment]
Also; interestingly; based on some sketchy responses from Sonos on twitter, Airplay 2 will be only supported on their "latest products such as the PLAY:5 gen2 and PLAYBASE" . 

I really wonder how this will work; as users with large Sonos setups made up of differing products are certainly going to complain if they can only Airplay to one or two specific devices. 

Maybe the solution they are heading for is Airplay to the controller, which will then use the proprietary Sonos streaming to any grouped speakers? Although I really doubt this is something Apple would be on board with.

We'll wait and see, I guess, but not holding out much hope of being able to Airplay to my Play:1's!

**Comment by leoneleone** [comment]
@alexlewer 
You are correct about Sonos supporting Airplay 2 only on their newer speakers. I believe this will be opened up eventually to older Sonos devices but we might be waiting a while for that. It will be difficult to tell until official support is released, but it appears you can add a gen2 speakers to a Grouped Room(s) and that will make those Sonos speakers Airplay 2 playable. So you might not need to replace all your Sonos speakers with new ones, just adding a Sonos ONE, or two 😛, could do it depending on your setup.

**Comment by leoneleone** [comment]
@ebaauw 

iOS 11.2.5 (beta7/GM) Home.app now supports the Speaker service.
Have you tested 11.2.5 yet?

**Comment by fraannk** [comment]
I still get "Not Supported". 🙁 

![img_c1215413a54d-1](https://user-images.githubusercontent.com/11140089/35301471-e29e199a-008b-11e8-8e90-a0e03f8ffc22.jpeg)

**Comment by ebaauw** [comment]
I fear we won't see anything before Airplay2 is released.  And it won't be at the introduction of the HomePod, next month...

**Comment by staticnz** [comment]
Hi, any updates on this with 11.3 beta 1 being released and also the final 11.2.5 with support for the HomePod? I've tried both with the "speaker" service type but still shows as unsupported. I wonder if Apple has set a different type?

**Comment by ebaauw** [comment]
11.2.5 offers no changes.  I haven’t yet tried 11.3 beta 1.  From what I read, it seems to provide some (buggy) Airplay2 support.  The only Airplay2 speaker available today seems an AppleTV on tvOS 11.3 beta.  I only have one AppleTV and won’t run any beta on it.  From what I read, Apple’s Home app treats the Airplay2 speaker as accessory, using the Airplay2 protocol, instead of HAP.  This means it won’t be possible for homebridge (which uses HAP) to provide speaker support to Apple’s Home app, nor to Siri.  This means our options are limited to an Airplay2 version of Airsonos, or Sonos’ native Airplay2 support.  It looks like Sonos are keen on killing HomePod before it grows, looking at their recent price cut of the Sonos One, so my bet is on Sonos Airplay2 support.
