### ISSUE TITLE
How to start with Radio xyz?

### ISSUE THREAD

**Issue by mensa84** [ebaauw/homebridge-zp#213]
Hello,

the plugin is working and I am able to play and pause my rooms.

But how can I start playing a specific (favorite?) radio station?

**Comment by ebaauw** [comment]
Include _Active Identifier_ in the HomeKit scene (using Eve or another decent HomeKit app).  The numeric value corresponds to the TV input position.  Make sure to set `"tv": true` in config.json so the favourites are exposed.

**Comment by mensa84** [comment]
Sorry, I don't understand TV position. How can I find out my TV position for that radio station?

**Comment by ebaauw** [comment]
Set `"tv": true` in config.json.  Pair the standalone TV accessory/ies with HomeKit, using the Home app.  Select the corresponding input channel in the TV accessory in the Home app.  Check in the Eve app, what the corresponding _Active Identifier_ is.  Include that in the HomeKit scene.

In their infinite wisdom, Apple decided we don't need TV support in HomeKit, and only shows TV accessories in the Home app.  And, of course, they cannot be bridged.  As Home doesn't support custom services nor characteristics, you need to create/edit the scene in a decent HomeKit app, but after that, you can recall the scene from Home or Siri,
