### ISSUE TITLE
Minor warning about nameScheme property

### ISSUE THREAD

**Issue by i814u2** [ebaauw/homebridge-zp#222]
#### Issue
On startup, plugin complains about invalid key in the config.json. It looks like it was removed in this commit: 5871b3b5fe319ec8defe49dc168674c844ec389d but there is still a reference to it in the README.md file.
It's just a warning in the logs, so it shouldn't cause problems.

I thought I'd post this issue to help others, as I didn't notice this called out in any release notes. 
I can easily remove from the config.json, I was just doing some research to make sure that was going to be fine, and see if I could find out what happened (or what I missed).

#### Log Messages
```
[Sonos] warning: config.json: nameScheme: invalid key
```

#### Debug Files
(skipping the debug log, since this doesn't seem needed in this case. but, let me know if I'm mistaken)

**Comment by ebaauw** [comment]
Removed the mention in README.
