### ISSUE TITLE
Error when queue is empty

### ISSUE THREAD

**Issue by mrygaard** [ebaauw/homebridge-zp#24]
To start with, thanks for a great plugin.
When my Sonos queues are empty I have noticed the following error in the log:

"...Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Play..."
(in apple Home App - No Response)

If I add some music to the queues with another ZP, there's no error and I can start/stop and change volume

**Comment by ebaauw** [comment]
Yes, this is how Sonos works.  When no input is selected (or TV on a PlayBar or an empty playlist), the speaker doens’t accept a Play command and returns UPnP error 500. 

The speaker actually indicates to the app (or to homebridge-zp) which actions (Play/Pause, Next, Previous, ...) can be issued, depending on it’s current state.  You won’t get these errors in the Sonos app, as Play will be greyed out when it’s not available.  However, in homebridge-zp, I cannot grey out a characteristic.  Temporary removing the characteristic would delete it from any HomeKit scenes or rules, so my only option is to return the error to the HomeKit app.  Apple’s Home app treats all errors as “No response”.
