### ISSUE TITLE
Issues after latest homebridge update (homebridge 0.4.28)

### ISSUE THREAD

**Issue by leoneleone** [ebaauw/homebridge-zp#25]
> [10/13/2017, 9:25:13 AM] ====================
> [10/13/2017, 9:25:13 AM] ERROR LOADING PLUGIN homebridge-zp:
> [10/13/2017, 9:25:13 AM] Error: Plugin /usr/local/lib/node_modules/homebridge-zp requires Node version of ^6.10.3 which does not satisfy the current Node version of v7.1.0. You may need to upgrade your installation of Node.
>     at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:63:11)
>     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:136:14)
>     at Array.forEach (native)
>     at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:132:22)
>     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:51:24)
>     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
>     at Module._compile (module.js:573:32)
>     at Object.Module._extensions..js (module.js:582:10)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)
>     at Module.runMain (module.js:607:10)
>     at run (bootstrap_node.js:420:7)
>     at startup (bootstrap_node.js:139:9)
>     at bootstrap_node.js:535:3
> [10/13/2017, 9:25:13 AM] ====================

I'm not sure what the problem is exactly but everything was working perfectly before updating home bridge today.

**Comment by ebaauw** [comment]
Are you sure you installed the released homebridge v0.4.28 from npm, not the latest commit form GitHub?

**Comment by leoneleone** [comment]
I downloaded straight from github. 

Thanks for the info and the recommendation 👍🏼
