### ISSUE TITLE
volume not change equally in one group

### ISSUE THREAD

**Issue by delai** [ebaauw/homebridge-zp#31]
I have 1 play5, 1 play3, 2 paired play1 in one group. delete "speaker: true" in config.json

As change the volume of ANY player in Home APP, volume of others automatically changed to the same number. BUT, this normal is only happened in Home APP. Actually, play5 changes a lot and others change a little every time.

Is this all be normal?

**Comment by ebaauw** [comment]
Yes, the volume control from the Sonos service provided by homebridge-zp is linked to the group volume.  It behaves the same as the group volume in the Sonos app.

To control the individual rooms in a group, set `"speakers": true` and use the volume control from the Speakers service.
