### ISSUE TITLE
Selecting prefered playlist

### ISSUE THREAD

**Issue by jnaeff** [ebaauw/homebridge-zp#32]
Is there a way to define a playlist to play with hitting a button in homekit.

**Comment by ebaauw** [comment]
Not at the moment, see #8.

**Comment by QuinnDD** [comment]
Maybe not with this plugin but there is a way, use Http-sonos api. https://github.com/jishi/node-sonos-http-api. Install this on your system. Install Http-homebridge plugin on your homebridge and simply use the url from the http songs api to start your playlist playing in the  Http-homebridge plugin.

**Comment by ebaauw** [comment]
See #8, homebridge-zp@1.0.0 allows selection of Sonos favourites as defined in the Sonos app.
