### ISSUE TITLE
Alarms are not showing up as switches.

### ISSUE THREAD

**Issue by Segelfeldt** [ebaauw/homebridge-zp#35]
In my config file i have set
`"alarms": true`

And my homebridge log shows the following

> [2018-5-10 11:37:30] [ZP] Bedroom Sonos: alarm Top 100 tracks currently in Sweden (06:40:00) changed from undefined to false
> [2018-5-10 11:37:30] [ZP] Bedroom Sonos: alarm Top 100 tracks currently in Sweden (06:34:00) changed from undefined to false
> [2018-5-10 11:37:30] [ZP] Bedroom Sonos: alarm Top 100 tracks currently in Sweden (06:31:00) changed from undefined to false
> [2018-5-10 11:37:30] [ZP] Bedroom Sonos: alarm Top 100 tracks currently in Sweden (06:25:00) changed from undefined to false
> [2018-5-10 11:37:30] [ZP] Bedroom Sonos: alarm Sonos Chime (20:11:55) changed from undefined to false

But i do not see any switches for my alarms, the plugin adds switches for my speakers and they work perfectly.

**Comment by ebaauw** [comment]
The alarms aren’t exposed as switches - I don’t want Siri to mess with them inadvertedly.  They’re exposed as a custom service, with an _Enabled_ characteristic.  Unfortunately, Apple’s Home app doesn’t support that, but other HomeKit apps do.
