### ISSUE TITLE
Support for Nightsound / Speech Enhancement

### ISSUE THREAD

**Issue by badrabbit** [ebaauw/homebridge-zp#38]
Since there is support for things like volume, mute, bass, treble and loudness, i'd like to know if it's possible to add support for **Nightsound** and **Speech Enhancement**?

Right now i'm able to toggle night sound on/off with homebridge-http plus the SONOS HTTP API. But it's unreliable for me an because it's a simple switch it doesn't get the current state.

Is implementation planned maybe?

**Comment by ebaauw** [comment]
Did some sniffing and it would seem the PlayBar sends event notifications for these settings, so getting the state won't be an issue.

What will be an issue is that these controls are available only when the PlayBar (or other home theatre zone player) is playing TV (the optical audio in).  I haven't been able to show controls in HomeKit dynamically.  Consequently, these settings will be visible all the time and HomeKit will return an error to the user, when s/he tries to change them while the input is not on TV.

**Comment by badrabbit** [comment]
Great, thank you!

**Comment by jjross** [comment]
Sorry, I'm running 0.3.14 and I don't see these characteristics exposed.  What I would love to do is schedule a HomeKit automation that will set night mode at night and then turn it back off at sunrise.  

Is this possible?  This is my config:

        {
            "platform": "ZP",
            "service": "speaker",
            "brightness": false,
            "speakers": false
        },

**Comment by ebaauw** [comment]
Apple’s Home app doesn’t support custom characteristics; you need to use another HomeKit app.

**Comment by jjross** [comment]
I tried Eve and “Home” and neither seemed to show the details on my playbase.

**Comment by ebaauw** [comment]
Sorry, I read over the config.json: you need to set `”speakers”: true` as these characteristics are exposed under the _Speakers_ service.

**Comment by jjross** [comment]
Got it! Thanks!
