### ISSUE TITLE
current track

### ISSUE THREAD

**Issue by henkied** [ebaauw/homebridge-zp#42]
HI @ebaauw Is it possible to see the current track in the home kit app? I now have this config file, but do not see anything :)

I can see the current track in the homebridge log file:

[2018-8-12 12:24:50] [ZP] Tv Sonos Sonos: set current track from "ELLIE GOULDING - ARMY" to "ALL THINGS UNDER THE SUN"

  "platform": "ZP",
             "service": "fan",
             "brightness": true,
             "speakers": true,
             "CurrentTrack": true

**Comment by ebaauw** [comment]
Apple’s Home app only provides limited HomeKit support.  You need another HomeKit app, like Eve to see the track (and other characteristics).

**Comment by henkied** [comment]
A i see thx for your reply
