### ISSUE TITLE
Sonos v9.1 breaking change

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-zp#46]
Sonos v9.1 seems to have a breaking change in how it handles groups.  Best not update your Sonos system yet.  See https://github.com/bencevans/node-sonos/issues/332.

**Comment by ebaauw** [comment]
Looks like homebridge-zp still works with Sonos 9.1.

**Comment by magnlund** [comment]
I have already updated and it does not seem to be working at all. Does Sonos support accepting downgrade???

**Comment by ebaauw** [comment]
Did you restart homebridge after the update?  When the zoneplayer reboots, it loses any open subscriptions, so homebridge-zp no longer receives event notifications.  At least until it renews the 
subscriptions, which might take up to 30min.

Afaik, Sonos doesn’t provide any means to downgrade the firmware.

**Comment by magnlund** [comment]
The only script I use is node-sonos which runs on a RPI which has been restarted. Besides this I have factory reset all 3 zoneplayers

**Comment by ebaauw** [comment]
If this is unrelated to homebridge-zp, then please discuss this with the node-sonos issue.

**Comment by magnlund** [comment]
Strange
I registred this at node sonos and you replied from there. Please clarify

Sent from ProtonMail mobile

-------- Original Message --------
