### ISSUE TITLE
Homebridge music level not the same as in the Sonos app

### ISSUE THREAD

**Issue by fraannk** [ebaauw/homebridge-zp#47]
Hello, I noticed something today. When I set the level for all my speakers (which are grouped) to the same level, they are not actually the same level. 

When I set my speakers to 17% in the Home app: 
![HomeKit screenshot](http://f.cl.ly/items/0q341U3g1D2Y381t1I2N/IMG_2143.jpg)

The level is not equal in the Sonos app: 
![Sonos app screenshot](http://f.cl.ly/items/1I2k3o3H1Y1t3J3D1A1Q/IMG_2144.jpg)

Any ideas? 

EDIT: If I then fix the level so they're all the same in the Sonos app, they are the same in the Home app. But if I then touch them in the Home app again, it offsets.

**Comment by ebaauw** [comment]
You’re setting the level of the _Sonos_ accessory, which is the group volume.  To set the volume of the individual zones, use the _Speaker_ accessory instead.

**Comment by fraannk** [comment]
Yes, I **want** to set the group volume, but for some reason they are not at the same volume even if I the home app shows them at the same percentage. :)

**Comment by ebaauw** [comment]
The Home app only shows the group volume under the _Sonos_ accessory. You need to look at the _Speaker_ accessory to see the volume of the individual zones in HomeKit. See 
https://github.com/ebaauw/homebridge-zp#speakers

**Comment by fraannk** [comment]
But why, when I set the individual zone volume to the same, and I then change the group volume, the individual volume is not the same anymore? (if that makes sense)

**Comment by ebaauw** [comment]
Do you set the individual volumes from the Sonos app?

**Comment by fraannk** [comment]
I've tried both :) And when I set them to the same in the Sonos app, and change the group volume in the Sonos app, the individual speakers are on the same level, but when I change the group volume in the home app, they become offset for some reason. I don't believe this error was there a couple months ago.

**Comment by ebaauw** [comment]
That’s very odd.  As far as I know, homebridge-zp issues the same command to set the group volume as the Sonos app.  Could you create a debug log file and attach that.  See 
https://github.com/ebaauw/homebridge-hue#debug-log-file

**Comment by fraannk** [comment]
I couldn't get the command to work since I use 'pm2' to start homebridge at boot. But I got the logs out another way. Get them [here](http://f.cl.ly/items/3C061i311A2X0I0l3S16/logs.zip)

In the output log it seems like when I use the Home app to change the group volume the output is: 
`[ZP] Living Room Sonos: group volume changed from 15 to 20`

But when I use the Sonos app, the output is: 
`[ZP] Living Room Sonos: set group volume from 15 to 20`

Dunno if that helped, but thanks so far 👍

**Comment by ebaauw** [comment]
> In the output log it seems like when I use the Home app to change the group volume the output is:
> But when I use the Sonos app, the output is:

Yes, that's to tell the difference between changes from HomeKit, that need to be forwarded to the Sonos, vs changes from Sonos (or other apps), that need to be reflected in HomeKit.

>> Do you set the individual volumes from the Sonos app?
> I've tried both :) 

No, you didn't.  You're not exposing any _Speaker_ service, so all you can see and set from HomeKit are the group volumes.  When the players are grouped, all the _Sonos_ services are mapped to the same group volume, see the README.

```
[2018-9-11 18:40:09] [ZP] Living Room Sonos: group volume changed from 15 to 20
[2018-9-11 18:40:09] [ZP] Living Room Sonos: set group volume from 15 to 20
```
I'm a bit worried that these messages have the same timestamp.  Did you change the volume from the Home app and from the Sonos app in the same second?  Unfortunately, there's no debug messages in the log, so I cannot see what's really going on.  I really need the output of `homebridge -D` for that.

**Comment by fraannk** [comment]
> No, you didn't.


Well, before sending the log I tried enabling the _Speaker_ service, but since that only made it possible to change the volume of the individual speaker, and didn't fix my problem when changing the group volume, I disabled it again. 🙂 

> Did you change the volume from the Home app and from the Sonos app in the same second?


No, I actually didn't... Probably 10-20 seconds in between. 

> I really need the output of homebridge -D for that. 


I'll try and see if I can get it 👍
