### ISSUE TITLE
No service in Home-app

### ISSUE THREAD

**Issue by hmook** [ebaauw/homebridge-zp#48]
Looks like the Homebridge-zp is reconized but gives me the following feedback (in Dutch):

"
Niet geschikt
Dit accessoire wordt momenteel niet ondersteund door de Woning-app
"

Is there anything I can do to fix this?

**Comment by ebaauw** [comment]
Change the `"service"` setting in config.json, see https://github.com/ebaauw/homebridge-zp#configuration.
