### ISSUE TITLE
Sonos Alarms crash due to TypeError of 'Service' undefined

### ISSUE THREAD

**Issue by mchl-btlr** [ebaauw/homebridge-zp#51]
Having "Alarms" set to true, ZP works without problems as long as I don't add any alarm.
As soon as there is an alarm, ZP crashes during boot with this message:

> [2018-10-3 10:53:25] [ZP] uncaught exception                                                               
> TypeError: Cannot read property 'Service' of undefined                                                     
>     at new ZpAlarm (/usr/local/lib/node_modules/homebridge-zp/lib/ZpAlarm.js:42:25)                        
>     at new ZpAccessory (/usr/local/lib/node_modules/homebridge-zp/lib/ZpAccessory.js:125:31)               
>     at listen (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:179:27)                         
>     at Server.server.listen (/usr/local/lib/node_modules/homebridge-zp/lib/ZpPlatform.js:255:12)           
>     at Object.onceWrapper (events.js:313:30)                                                               
>     at emitNone (events.js:106:13)                                                                         
>     at Server.emit (events.js:208:7)                                                                       
>     at emitListeningNT (net.js:1387:10)                                                                    
>     at _combinedTickCallback (internal/process/next_tick.js:136:11)                                        
>     at process._tickCallback (internal/process/next_tick.js:181:9)  

This is my HB/ZP setup:
root@homebridge1:~/.homebridge# npm -g list --depth=1                                         
/usr/local/lib                                                                                             
+-- homebridge@0.4.45                                                                                      
| +-- chalk@1.1.3                                                                                          
| +-- commander@2.8.1                                                                                      
| +-- hap-nodejs@0.4.47                                                                                    
| +-- node-persist@0.0.8                                                                                   
| +-- qrcode-terminal@0.11.0                                                                               
| `-- semver@5.0.3

+-- homebridge-zp@0.2.34                                                                                   
| +-- he@1.2.0                                                                                             
| +-- homebridge-lib@1.0.9                                                                                 
| +-- request@2.88.0                                                                                       
| +-- semver@5.5.1                                                                                         
| +-- sonos@0.22.2                                                                                         
| `-- xml2js@0.4.19 

Any guess?

**Comment by ebaauw** [comment]
I’m afraid this is a bug.  Not sure when it was introduced, but I’ll provide a fix coming week.

**Comment by ebaauw** [comment]
Fixed in v0.2.35.

**Comment by mchl-btlr** [comment]
Thanks alot! It is working again.
