### ISSUE TITLE
Switch and brightness

### ISSUE THREAD

**Issue by dariusrosendahl** [ebaauw/homebridge-zp#57]
First of all, great plugin!

I'm a bit confused though. I got it working by setting ```"service": "fan",``` or ```"service": "light",```.

However when I set it to switch the brightness control doesn't work even though it says so in the readme. Is there any way to to get this to work with speaker or switch?

Thanks!

**Comment by ebaauw** [comment]
The `switch` and `speaker` settings use _Volume_ by default.  You need to set `brightness` in config.json to use _Brightness_ instead.

**Comment by dariusrosendahl** [comment]
I did set the brightness. However the switch just stays an on/off switch.

```
{
    "platform": "ZP",
    "service": "switch",
    "brightness": true,
   "speakers": false
},
```

**Comment by ebaauw** [comment]
That’s a limitation of the Home app.  The _Brightness_ should be recognised by Siri, though.  See 
https://github.com/ebaauw/homebridge-zp/issues/10#issuecomment-270743358.

**Comment by dariusrosendahl** [comment]
I created PR #59 to explain this limitation in the readme.
