### ISSUE TITLE
How to determine model number?

### ISSUE THREAD

**Issue by jjross** [ebaauw/homebridge-zp#58]
I would like to support this “Add (read-only, boolean) TV characteristic to Sonos service for the Playbar, so enable HomeKit automations when turning on or off the connected TV” and I have a Playbase. Happy to get you the model number but just need to know how.

**Comment by ebaauw** [comment]
Homebridge-zp exposes it as the _Model_ in the _Accessory Information_ service.  Apple’s Home app shows this in the bottom of the _Settings_ screen.

**Comment by jjross** [comment]
Ok, looks like it’s ZPS11

Look correct?

**Comment by ebaauw** [comment]
That looks like a model number.  Are you sure it’s for the Playbase?  Just asking because ZPS1 and ZPS12 are used for the Play:1, but I’m not sure if ZPS12 means ZPS1 revision 2 or simply ZPS twelve.

**Comment by jjross** [comment]
That’s the value the plugin is reporting.

**Comment by ebaauw** [comment]
Could you try the latest version of homebridge-zp?

**Comment by jjross** [comment]
Looks like it works!  When I view the characteristics in the "Home" app (not Apple's home app) I can see:

-Track: Tv
-TV: Yes

I assume this is correct?  Is there anything else I need to check?

**Comment by ebaauw** [comment]
No, that’s what I expected/hoped for.

**Comment by jjross** [comment]
Awesome work. Thanks for the quick turnaround.
