### ISSUE TITLE
Support HomeKit Television service

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-zp#62]
See https://github.com/nfarina/homebridge/issues/2104.

**Comment by vswraith** [comment]
If I am on 12.2 beta should I be seeing Sonos in the remote app? Any setting to activate it?

**Comment by ebaauw** [comment]
Not looking good - it would seem that Apple only supports a single _TV_ accessory per HomeKit bridge (i.c. homebridge instance).  See https://github.com/KhaosT/HAP-NodeJS/issues/641.

Also still some instabilities and changes between beta versions, see https://github.com/KhaosT/HAP-NodeJS/issues/645 and https://github.com/KhaosT/HAP-NodeJS/issues/646.

**Comment by ebaauw** [comment]
v0.3.11 has experimental support for the _Television_ service in iOS 12.2, to get a feeling what it would look like.
- To try this, you need to run iOS 12.2 beta on your iPhone or iPad;
- Set `"tv": true` in config.json, and homebridge-zp will expose four additional services per zoneplayer:
  - One _Television_ service;
  - One _Television Speaker_ service;
  - Two _Input Source_ services, linked to the _Television service.
- The _Television_ service should appear as a tile in Apple's Home app (on iOS 12.2 beta).  Pressing the tile toggles the "television" active (on) or inactive (off), but doesn't do anything yet.  When holding the tile, you see two buttons: _Input_ and _Settings_.  I've hardcoded two inputs, "Uno" and "Due" (to check the fixed order), neither are functional yet.  Under settings you can rename the inputs.
- When selecting the AppleTV widget in the Control Centre (swipe up from the bottom of your iPhone screen, or swipe down on the upper right of your iPad screen), you should find a single new device, next to your AppleTV(s).  Somehow, the widget randomly selects a single zoneplayer, instead of showing them all.  You should be able to control the zoneplayer, using the _Play/Pause_ button The other buttons are not yet functional.
- To control the volume, use the hardware _Volume Up_ and _Volume Down_ buttons while in the widget.  In beta 3, you might need to change devices to your AppleTV and back to the zoneplayer, before these buttons work.

**Comment by fugazzy** [comment]
Would iz be possible to include inputs (like TV on the Amp) and Favourites (from Sonos) in the TV service?
I know, they will not be visible in 3rd party apps - only in Apples Home App
But by using scenes they will be usable

**Comment by ebaauw** [comment]
> Would it be possible to include inputs (like TV on the Amp) and Favourites (from Sonos) in the TV service?

That was my main reason to try and expose the zoneplayers as televisions.

> I know, they will not be visible in 3rd party apps - only in Apples Home App

And only one of them (random) will be available in the _Remote_ widget.  But, luckily, you don't need that for the input selection.

> But by using scenes they will be usable

Guess again :-(  In Apple's Home app, you can only select the TV service for On/Off control.  Eve does show the scene, but with empty actions.  Consequently, you cannot recall the scene, because Eve brings out the _Edit Scene_ dialogue.

**Comment by fugazzy** [comment]
I have a TV Service running for my Sony TV (homebridge-bravia-tvos) and there I can switch between DVBC and HDMI-Inputs ans Channels.
I can configure scenes in Apple Home to switch between DVBC and HDMI 2 and they work, even though this setting does not show up in e.g. EVE

**Comment by ebaauw** [comment]
Can you please post a screenshot of setting up the scene?  I’ve got my test setup on iOS 12.3 beta, maybe that’s the issue. Or maybe that I still exposed the _TV_ accessory bridged.

How do you recall the scene from Eve?  Or did you add some other settings that Eve does see?

**Comment by fugazzy** [comment]
![IMG_7278](https://user-images.githubusercontent.com/20287362/57100660-d6ff9a80-6d1f-11e9-8324-39562385ac25.png)
![IMG_7279](https://user-images.githubusercontent.com/20287362/57100661-d6ff9a80-6d1f-11e9-873a-c5bbab2043c9.png)
![IMG_7280](https://user-images.githubusercontent.com/20287362/57100662-d6ff9a80-6d1f-11e9-877b-28c4cbe66655.png)
![IMG_7281](https://user-images.githubusercontent.com/20287362/57100663-d6ff9a80-6d1f-11e9-87df-35c5100ccd38.png)
![IMG_7277](https://user-images.githubusercontent.com/20287362/57100665-d7983100-6d1f-11e9-8797-d639c0412fa6.png)

**Comment by ebaauw** [comment]
I need to check their code, but it would seem they expose the inputs twice: once as input service linked to the TV service for the Home app, and once as switch for the scene and the other apps.  Do you see a switch for each input?

**Comment by fugazzy** [comment]
After the first run I do see switches for each input / channel, but after force-quitting the Apple Home App I find everything nice in one place in the tile of the Sony TV

**Comment by ebaauw** [comment]
> I need to check their code, but it would seem they expose the inputs twice

No, they don't.

> After the first run I do see switches for each input / channel, but after force-quitting the Apple Home App I find everything nice in one place in the tile of the Sony TV

See https://github.com/nfarina/homebridge/issues/2192.  I'm not sure what to think of this, but it would seem you would only be able to create the scene with the input after the first run, before force-quitting the Home app.

**Comment by fugazzy** [comment]
The screenshots are from my scenes, not directly after the first start.
It works for me as described. 
The separate tiles seem to be a slow syncing problem that is gone after a wile or by force-quitting the app.
![IMG_7282](https://user-images.githubusercontent.com/20287362/57108112-1afb9b00-6d32-11e9-88a4-bb5c01ebfaea.gif)

**Comment by fugazzy** [comment]
I tried the new version 38 in my testing instance, with TV service.
Input TV ist showing up for my Sonos Amp and a switch of the input is detected and shown in the Home App (One and TV) when I switch eg. in the Sonos App.
What is not working is switching inputs from the Home App.

**Comment by ebaauw** [comment]
homebridge-zp@1.0.0 supports non-bridged Television accessories in Apple's Home app and in the Remote widget.  The Home app supports selection of external input, groups, and favourites (see #8).  The widged supports volume up/down (hardware volume buttons), play/pause, and next/previous track (right/left button).  TODO: next/previous input (up/down button).  I'm open for suggestions for the other buttons, and for the _View TV Settings_ in the details screen.

When `tv` is true in config.json, homebridge-zp creates an external, non-bridged TV accessory for each zone (room).  It needs to be paired to HomeKit separately.  The TV service in this accessory is linked to the Sonos service, which is still needed for other HomeKit apps.  Somehow accessories with a TV service are invisible to other HomeKit apps.

Please let me know what you think.

**Comment by ebaauw** [comment]
Some more technical details:
- You can specify the range of ports to be used by the non-bridged TV accessories in `config.json`, using, e.g. `"ports": { "start": 51827, "end": 51839 }` at the top level;
- To check that the HAP server for each accessory is running, use
  ```
  $ sudo netstat -an -p tcp | grep LISTEN
  ```
- To check the HAP server has announced itself through Bonjour, use the `hap` command-line utility (from homebridge-lib).:
  ```
  $ hap
  ```
  On macOS, you can also use:
  ```
  $ dns-sd -B _hap._tcp
  ```
  On Raspbian, you can also use:
  ```
  $ avahi-browse _hap._tcp
  ```
  Somehow _Bonjour Browser_ (on macOS) and _Discovery_ (on iOS) don't show `_hap._tcp` announcements.  In (32-bit) version 1.5.6 of _Bonjour Browser_, you can still add it in the _Preferences_, but the latest (64-bit) version no longer support this.
- Homebridge generates the the username (fake mac address) for the accessory from its UUID.  The four-hex-digit suffix to the accessory name is derived from this username.
- homebridge-lib generates the accessory UUID from its serial number;
- homebridge-zp sets the accessory serial number to `TV_`_xxxxxxxxxxxx_, where _xxxxxxxxxxxx_ is the zone player's mac address;
- To run multiple instances of homebridge-zp on your network (e.g. for testing), each instance needs to use different serial numbers.  I will add a `"tvIdPrefix"` setting in config.json for this.

**Comment by ebaauw** [comment]
Need to use up and down arrows in the widget to change current input.  See https://github.com/ebaauw/homebridge-zp/issues/8#issuecomment-515714744.
