### ISSUE TITLE
Feature: Stereo Balance Presets

### ISSUE THREAD

**Issue by chietanjain** [ebaauw/homebridge-zp#64]
@ebaauw Thanks a million tons for this plug-in!!!

Would it be possible to add a feature to include 2 or 3 balance presents for a stereo pair?

Why I need this: I have two different listening positions in my living room. 

I know this can be tricky given the fact that stereo pairs can be created and separated dynamically, plus it may require complicated changes in the config.json, and I see that you are (rightly) averse to changes/additions to the config.json. So, I am making this request hoping youll be able to come up with something sometime! and solve this annoying process, to have to change the balance every time I shift listening position, in the sonos app. Perhaps a siri command or scene would be stereo nirvana!

**Comment by ebaauw** [comment]
I've been wanting to support _Balance_ for a long time, see #7, but it's quite challenging:
1. There isn't a _Balance_ endpoint on the zoneplayers.  Instead they seem to expose three _Volume_ "channels", _Master_, _RF_ and _LF_.  The Sonos app adjusts the _RF_ and/or _LF_ channel volume when changing the _Balance_.  A balance of 0% (middle) sets both channels to 100%; a balance of -100% (left) sets the _right_ channel to 0%; and a balance of 100% (right) sets the _left_ channel to 0%.;
2. I still haven't been able to figure out how to determine if a zone supports _Balance_.  All zones seem to report the three _Volume_ channels, irrespective of whether they support _Balance_.  It's not just supported for stereo pairs, but also for the Connect.  Counter-intuitively, it's not supported for the Playbar.

Ad 1) In line with the Sonos app, I've exposed _Balance_ in the _Speaker_ service as a percentage from -100% to 100%, in steps of 5%.  As this is a custom characteristic, neither Apple's Home app nor Siri support this.  However, you should be able to include this in a HomeKit scene using Eve, and then recall the scene from Siri.

Ad 2) I added logic to see if a zone is has slave zoneplayers.  Afaik this is only the case for stereo pairs and home theatre setups.  I already whitelisted the home theatre players (like PlayBase and PlayBar), so I won't expose _Balance_ for home theatre setups.  Also, I added a whitelist for zoneplayers that natively support stereo channels, like the Sonos Connect.

**Comment by ebaauw** [comment]
In v0.3.14.

**Comment by chietanjain** [comment]
@ebaauw, thank you for the patient response and for pointing me in the right direction. Apologies for not writing in earlier.

I haven't tried any other home app except the one from apple. Will give it a try and report back.

And thanks for this great plugin!
