### ISSUE TITLE
Power state vs mute state

### ISSUE THREAD

**Issue by mtjoernelund** [ebaauw/homebridge-zp#67]
When using either Eve Home or Home.app Mute state is prioritised over power (play/pause) state. 

In Eve this means that a player that is not playing anything still appears as on in all overviews because audio is on (i.e. player is not muted). 

Conversely in Home.app the player will appear as off in all overviews even when playing something as mute is off. 

I’ve tried to re-order the custom attributes in the eve home app but this makes no difference. Nor does hiding the audio (mute) attribute. 

Any chance that the priority/order of the attributes can be changed in the plugin or will that not work either?

**Comment by mtjoernelund** [comment]
Very basic config for this plugin. Service is defined as speaker to avoid mixing with other switches. Works very well apart from the issue with the overview in the apps. But I guess above answers my question, when mute is only mandatory property for speaker service it makes sense that this is what is prioritised. 

With regards to the Home app I think I am causing confusion. In the Apple build-in home app this plugin shows as unsupported here as well. I was referring to Matthias Hochgatterer‘s very excelente home app. Sorry about that and thanks for your clarification. Maybe I need to try using switch instead of speaker as service type and see how that works in my setup.

**Comment by ebaauw** [comment]
Love Matthias' Home app, but I don't think it allows you to sort the characteristics.

Yes, using `"switch"` instead should address this.
