### ISSUE TITLE
cannot SUBSCRIBE (412 - Precondition Failed)

### ISSUE THREAD

**Issue by sschuste** [ebaauw/homebridge-zp#68]
Hi Erik,

I have one question not directly regarding homebridge-zp. Since some days I get a HTTP 412 error from my Sonos system. I understand that this isn't a homebridge-zp issue, but do you have any idea where I could start to debug this message? Sorry to bother you and to misuse this platform for this but you might have seen this already. 

192.168.1.62 is my Sonos Playbar and ZP with two surrounding Play:1 connected to it. It was sometimes powered off in the last week. 

```
Apr 12 09:36:36 homePi homebridge[11994]: [4/12/2019, 9:36:36 AM] [ZP] Initializing platform accessory 'Wohnzimmer Sonos'...
Apr 12 09:36:37 homePi homebridge[11994]: [4/12/2019, 9:36:37 AM] [ZP] Wohnzimmer Sonos: cannot SUBSCRIBE http://192.168.1.62:1400/MediaRenderer/AVTransport/Event (412 - Precondition Failed)
Apr 12 09:36:37 homePi homebridge[11994]: [4/12/2019, 9:36:37 AM] [ZP] Wohnzimmer Sonos: subscribe to AVTransport events: 412
Apr 12 09:36:37 homePi homebridge[11994]: [4/12/2019, 9:36:37 AM] [ZP] Wohnzimmer Sonos: cannot SUBSCRIBE http://192.168.1.62:1400/MediaRenderer/GroupRenderingControl/Event (412 - Precondition Failed)
Apr 12 09:36:37 homePi homebridge[11994]: [4/12/2019, 9:36:37 AM] [ZP] Wohnzimmer Sonos: subscribe to GroupRenderingControl events: 412
Apr 12 09:36:37 homePi homebridge[11994]: [4/12/2019, 9:36:37 AM] [ZP] Wohnzimmer Sonos: coordinator for group Wohnzimmer

```

Gruß,
Stefan

**Comment by ebaauw** [comment]
There's a limit to the number of simultaneous subscriptions a zoneplayer can handle (like 16 or 32, if I remember correctly).  The only time I've ever seen subscribe fail is when this limit was reached (hence my efforts to make sure homebridge-zp cancels the subscriptions before exiting).  Unfortunately the bastards at Sonos have removed the diagnostics page on the player, where you could check the active subscriptions.

Some troubleshooting hints:
- Do you have other Sonos players?  Are they working?
- Can you control the PlayBar from the Sonos app?  It makes similar subscriptions.  Also, double-check in the Sonos app if your player has a pending update.
- Is homebridge-zp listening on the 192.168.1.x subnet?  Check for the message in the homebridge log.  Can you access homebridge-zp's web server from your web browser?  See https://github.com/ebaauw/homebridge-zp#troubleshooting.
- Did you power-cycle the PlayBar?  I find that the Sonos players boot too soon after a power failure, typically before my Internet connection is back up, see #53.

**Comment by sschuste** [comment]
No, other Sonos players don't work correctly. You can start a song by double clicking but it's not possible to stop it again as all handles (back, stop, forward) are greyed out. The volume slider is set to zero but the music plays. However, volume can be set through the slider. So the player is working somehow but not completely. This happens on my Mac as well with the iPhone app.

I'm using a simple network without any subnetting and without any repeaters. So all components are listening and working in the same network 192.168.1.0/24. The player is connected via Ethernet, all the rest is going over the air.

Homebridge-zp has a builtin web server? The world is full of wonders. Ok, I try the troubleshooting you mentioned. Thanks for the link.

I power-cycled the Playbar and the Play:1s intentionally due to the Greta-effect to save power. This thingie is running all day long and nobody is at home to use it. So I decided to switch it off what turns out as a bad idea meanwhile.

Thanks for your help. I'm getting a better understanding of this Sonos machine.

Stefan

**Comment by ebaauw** [comment]
> No, other Sonos players don't work correctly. You can start a song by double clicking but it's not possible to stop it again as all handles (back, stop, forward) are greyed out. The volume slider is set to zero but the music plays. However, volume can be set through the slider. So the player is working somehow but not completely.

Sounds like the Sonos app cannot subscribe to the other players either.  It can send commands, but it doesn't receive any notifications back from the player (incl. whether to enable play/pause, next/previous track, etc).

> This happens on my Mac as well with the iPhone app.

This rules out a firewall issue on your PC or Mac.

> I'm using a simple network without any subnetting and without any repeaters.

And this rules out a firewall issue in your network.

So there's either a spanning tree issue in your network, or a common issue in all your players.  Did you check for pending updates in the Sonos app?

Can you double-check how you connect your Sonos speakers: if the PlayBar is connected by Ethernet, the other players should be connected over SonosNet, not to your home Wifi.  Check _About My Sonos System_ in the app: all players should report `WM: 0`.  You might check the _Network Matrix_ on your PlayBar: http:///192.168.1.62:1400/support/review.  See https://bsteiner.info/articles/hidden-sonos-interface for an explanation of that.

> So I decided to switch it off what turns out as a bad idea meanwhile.

I think they want to be always on.  It could be an issue with the order in which you started the players.  Could you power down all players, except the one (PlayBar?) that is wired to the network.  Check whether you can control that one, before powering the next player.  If indeed the PlayBar is wired, I would first power the satellite speakers before the other rooms/zones.  Check after each player whether all powered players work.

**Comment by Shep084** [comment]
Hi,
I’m having the same issue, did you find a solution?
Thanks
