### ISSUE TITLE
Fixed Devices in Config.json

### ISSUE THREAD

**Issue by niwre2019** [ebaauw/homebridge-zp#72]
Would it be possible to save Sonos devices in the configuration?  I have 2 Sonos speakers which are only connected, if I use these, since these are in the garden.  If I restart the Homebridge and forget to turn it on before then the devices in HomeKit are missing and I have to reconfigure them after another restart of the Homebridge.

**Comment by ebaauw** [comment]
That requires refactoring homebridge-zp to use to the dynamic platform model, see #1.  No ETA yet.

**Comment by niwre2019** [comment]
Thank you for your response.
