### ISSUE TITLE
Stopping working fine, playing not at all

### ISSUE THREAD

**Issue by peter99330** [ebaauw/homebridge-zp#73]
Hi,

I have a very basic configuration of the plugin:
`{
            "name": "Sonos",
            "service": "switch",
            "brightness": true,
            "platform": "ZP"
        }`

Turning the accessory on however does not do anything. Stopping the music works perfectly every time, but there is no way to resume playing through Homekit once the music is stopped.
This has worked before but stopped working a few days back. 
Any thought? The switch in the Home app is not affected. It turns on and stays on. It just does not have any effect on the actual sonos device.

There is log output when turning "off": `Kitchen Sonos: power (play/pause) changed from true to false` but none whatsoever when trying to turn sonos back on.

**Comment by ebaauw** [comment]
In the Sonos app, does the zoneplayer have a selected input?  When it doesn't there's nothing to play.  homebridge-zp cannot handle that without support for input selection (#8, #32).

**Comment by peter99330** [comment]
It does. Does not matter which service (Apple Music, TuneIn, Spotify).
When starting music via the Sonos app, then stopping it via Siri/Home it stops but is still selected in the app. Restarting the music only works by pressing play in the Sonos app, not via Siri/Home.

**Comment by ebaauw** [comment]
That’s odd.  Can you please capture and attach a debug log file?  See https://github.com/ebaauw/homebridge-hue#debug-log-file.
