### ISSUE TITLE
Support for Linn Streamers / Openhome

### ISSUE THREAD

**Issue by bubffm** [ebaauw/homebridge-zp#76]
Not really an issue but more a question:

Is there any way to support Linn DS Streamers within Homebridge-ZP? I own three Linn DS Streamers and would love to integrate soem basic functionality in my homebridge setup. I remember from many years back when I had a mixed setup of Linn and Sonos players that I could control these from the same Control point, so there must be some compatibilities.

Linn Streamers are using the extended Upnp Protocol Openhome wiki.openhome.org
and can also be controlled by the Linn LPEC Telnet stack https://docs.linn.co.uk/wiki/index.php/Developer:LPEC#LPEC_Examples

Any chance to control these streamers via homebridge-zp or any pointers as to which plugin might work with these players.

Many thanks

**Comment by ebaauw** [comment]
Can you control them from the Sonos app?

**Comment by bubffm** [comment]
just installed the App. No, doesnt seem to find anything. It wants me to press a button on my Sonos, which I dont have.

**Comment by ebaauw** [comment]
> I could control these from the same Control point, so there must be some compatibilities.'
> Linn Streamers are using the extended Upnp Protocol Openhome
> just installed the App. No, doesnt seem to find anything.

So I guess while both use UPnP to describe their SOAP services, they offer different services.  The services homebridge-zp consumes from the Sonos zoneplayers are hard-coded; it doesn't use the service discovery part.

> can also be controlled by the Linn LPEC Telnet stack

That's a completely different API.

> Any chance to control these streamers via homebridge-zp

Sorry, no, I don't see any leverage supporting two different APIs in the same plugin.  It would be less effort and easier maintenance to create a new plugin.

> any pointers as to which plugin might work with these players.

No.

**Comment by bubffm** [comment]
No problem. Thanks for looking into it.
