### ISSUE TITLE
Sonos ZP's Not Initializing

### ISSUE THREAD

**Issue by lightingmna2003** [ebaauw/homebridge-zp#77]
Relatively new to Homebridge, but a long time user of Sonos, and wanted a way to be able to control my non-AirPlay2 devices from my phone etc. I'm running Homebridge on a Pi 3B. 

Read the instructions listed here.. https://www.npmjs.com/package/homebridge-zp#configuration, but I still cant add them individually on Homekit. Homebridge can see my Sonos Zones, and the individual speakers within those zones pretty easily, but I still cant add them on Homekit:

un  5 21:55:44 raspberrypi homebridge[3585]: [6/5/2019, 9:55:44 PM] [ZP] Initializing platform accessory 'Living Room Sonos'...
Jun  5 21:55:44 raspberrypi homebridge[3585]: [6/5/2019, 9:55:44 PM] [ZP] Initializing platform accessory 'Living Room 2 Sonos'...
Jun  5 21:55:44 raspberrypi homebridge[3585]: [6/5/2019, 9:55:44 PM] [ZP] Initializing platform accessory 'Kitchen Sonos'...
Jun  5 21:55:44 raspberrypi homebridge[3585]: [6/5/2019, 9:55:44 PM] [ZP] Initializing platform accessory 'Bedroom Sonos'...

My Sonos Speakers are running on the Sonos Wireless Mesh, and not on Wifi. I am using an old fashioned Sonos ZoneBridge to bridge between my network & my Sonos Network. All of my Sonos ZP's have static IP's set by DHCP. 

Any help would be greatly appreciated!

**Comment by ebaauw** [comment]
The Sonos accessories are bridged by homebridge; you cannot add them to HomeKit individually; they are added automatically when you add the homebridge accessory.
