### ISSUE TITLE
iOS 13 and Speakers

### ISSUE THREAD

**Issue by adavison007** [ebaauw/homebridge-zp#78]
Hi, nice plugin... in the native Apple Home app in ios13 will this plugin be able to show speakers like airplay2 devices?

**Comment by adavison007** [comment]
So I guess I've either set it up wrong or this is correct, EVE shows it as a speaker and gives full controls, Apple Home app says not supported, can this not show as a speaker? even if it cannot support all the features that Eve can? Thanks in advance, i'm hoping if this works I can use the coll ew features in iOS 13 for playing music from apple music etc?

![IMG_4666](https://user-images.githubusercontent.com/47482260/59146551-69622080-89e7-11e9-8f63-aa57b6103011.jpeg)

![IMG_4667](https://user-images.githubusercontent.com/47482260/59146552-6bc47a80-89e7-11e9-81e5-1c52c363e18c.jpeg)

![IMG_4668](https://user-images.githubusercontent.com/47482260/59146553-6cf5a780-89e7-11e9-98e8-2d6e80a6e323.png)

**Comment by ebaauw** [comment]
> in the native Apple Home app in ios13 will this plugin be able to show speakers like airplay2 devices?

No, Airplay 2 is a different protocol than HAP, which homebridge (and any HomeKit accessory) uses.

> Apple Home app says not supported, can this not show as a speaker?

Indeed, see https://github.com/ebaauw/homebridge-zp#configuration and https://github.com/ebaauw/homebridge-zp/issues/10#issuecomment-270743358.

**Comment by adavison007** [comment]
> > in the native Apple Home app in ios13 will this plugin be able to show speakers like airplay2 devices?
> 
> No, Airplay 2 is a different protocol than HAP, which homebridge (and any HomeKit accessory) uses.
> 
> > Apple Home app says not supported, can this not show as a speaker?
> 
> Indeed, see https://github.com/ebaauw/homebridge-zp#configuration and [#10 (comment)](https://github.com/ebaauw/homebridge-zp/issues/10#issuecomment-270743358).

Thanks for the response and your support, I must be doing something wrong.... I have it as a switch now and that works, but I cannot for the life of me get it to show in the apple home app with a speaker icon?

**Comment by ebaauw** [comment]
The only thing you're doing wrong is expecting that Apple's Home app could...

**Comment by adavison007** [comment]
Lol, I miss read your response, I chose to read “indeed” as positive.. lol.. well hopefully with the expanded controls in ios13 some form of integration can work as they are adding full speaker and music control support, hoping like I can add my tv now I will also be able to add speakers. Why Sonos just don’t update all the hardware to support airplay and HomeKit is beyond me

**Comment by jdtsmith** [comment]
Have you considered using the new television service, which has both on/off and volume (and input) control?

**Comment by ebaauw** [comment]
I’ve done more than considering it, see #62.
