### ISSUE TITLE
Zonespeaker not turning off in using homekit

### ISSUE THREAD

**Issue by mitchelp** [ebaauw/homebridge-zp#79]
Goodmorning,

Thank you for your awesome plugin for homebridge.

I am using it for a while now and since the last update I have some trouble with it.
When I restart homebridge everything is working just fine. But after a while my sonos speakers are not turning off anymore using homebridge-zp.

I have set it up as following:
Homebridge --> Homebridge-zp.
And I use homekit and Home 3 app to configure everything. When I try to turn off my sonos it won't turn off. I can mute it, but thats not really turning off.

Is there a known issue for this? Or does it need a upgrade.

My loggings says the following:
Turning ON: (working fine)
`Jun 12 06:00:04 raspberrypi homebridge[31290]: [6/12/2019, 6:00:04 AM] [ZP] Woonkamer Sonos: set group volume from 14 to 3
Jun 12 06:00:06 raspberrypi homebridge[31290]: [6/12/2019, 6:00:06 AM] [ZP] Woonkamer Sonos: set power (play/pause) from false to true
Jun 12 06:00:21 raspberrypi homebridge[31290]: [6/12/2019, 6:00:21 AM] [ZP] Woonkamer Sonos: set current track from "Radio 10" to "Zedd & Alessia Cara - Stay"`

Turning OFF: (not working)
`un 12 06:17:36 raspberrypi homebridge[31290]: [6/12/2019, 6:17:36 AM] [ZP] Woonkamer Sonos: power (play/pause) changed from true to false
Jun 12 06:17:38 raspberrypi homebridge[31290]: [6/12/2019, 6:17:38 AM] [ZP] Woonkamer Sonos: power (play/pause) changed from true to false
Jun 12 06:17:39 raspberrypi homebridge[31290]: [6/12/2019, 6:17:39 AM] [ZP] Woonkamer Sonos: power (play/pause) changed from true to false
Jun 12 06:17:39 raspberrypi homebridge[31290]: [6/12/2019, 6:17:39 AM] [ZP] Woonkamer Sonos: power (play/pause) changed from true to false
Jun 12 06:17:40 raspberrypi homebridge[31290]: [6/12/2019, 6:17:40 AM] [ZP] Woonkamer Sonos: power (play/pause) changed from true to false
Jun 12 06:17:40 raspberrypi homebridge[31290]: [6/12/2019, 6:17:40 AM] [ZP] Woonkamer Sonos: power (play/pause) changed from true to false`

Just nothing happening on turning off.

I really don't know whats wrong.

Versions:
[homebridge-lib.Lib] homebridge-lib v4.2.7, node 10.16.0, homebridge v0.4.50
homebridge-zp v0.4.3

I hope to receive some help over here.

**Comment by ebaauw** [comment]
Can you please capture and attach a full debug log, see https://github.com/ebaauw/homebridge-hue#debug-log-file.

**Comment by mitchelp** [comment]
Here you go:
https://pastebin.com/uRs4JbAh

**Comment by ebaauw** [comment]
> Here you go:

Sorry, I need a bit more than that.  Please run homebridge for several minutes, and turn the zoneplayer on and off from HomeKit several times during that time.  I need to see what commands homebridge-hue sends to the ZonePlayer, and how it responds.

> Ow and about the warnings:

Nothing to do with homebridge-zp.  You probably used different ways to install different versions of `node`, causing it to move from `/usr/local` to `/usr`.  What does `ls -l $(which node)` report?  And `ls -l $(which homebridge)`?
