### ISSUE TITLE
speakers not discovered

### ISSUE THREAD

**Issue by pelaxa** [ebaauw/homebridge-zp#80]
I Have my Sonos speakers on a separate clan.  I can open the Sonos app and discover them just fine, but the plugin does not seem to be able to discover anything.  the only lines I get in the log are:

6/15/2019, 10:38:10 PM] [Sonos] Initializing ZP platform...
[6/15/2019, 10:38:10 PM] [Sonos] homebridge-zp v0.4.3, node v10.16.0, homebridge v0.4.50
[6/15/2019, 10:46:11 PM] [Sonos] cleaning up...
[6/15/2019, 10:46:16 PM] [Sonos] exit

My config is:
{
            "name": "Sonos",
            "platform": "ZP"
}

starting Homebridge with -D 2>&1 did not show any additional logging and I do not seem to be able to find anything else to try.  Any advice?

**Comment by ebaauw** [comment]
Does homebridge run on the same network as the zoneplayers and the Sonos app?  The players are discovered through UPnP, which isn’t routable.

**Comment by pelaxa** [comment]
Yes it does.  I have a repeater setup just for this setup to work. Unless somehow this is communicating over a different port?

**Comment by ebaauw** [comment]
Most likely, the repeater is eating up the UPnP local subnet multicasts.  Check `upnp -z` on each side of the repeater.

**Comment by pelaxa** [comment]
I ran mirandaupnp (https://code.google.com/archive/p/miranda-upnp/downloads) on the subnet that is running homebridge and it does discover my speakers although it is a little slow.  Wireshark also shows SSDP packets between the two subnets.  Maybe an issue with how long discovery is run?

$ ./miranda.py

Miranda v1.3
The interactive UPnP client
Craig Heffner, http://www.devttys0.com

upnp> host list

No known hosts - try running the 'msearch' or 'pcap' commands

upnp> msearch

Entering discovery mode for 'upnp:rootdevice', Ctl+C to stop...

****************************************************************
SSDP notification message from 172.X.X.105:1400
XML file is located at http://172.X.X.105:1400/xml/group_description.xml
Device is running Linux UPnP/1.0 Sonos/50.1-65071 (ZPS3)
****************************************************************

****************************************************************
SSDP notification message from 172.X.X.104:1400
XML file is located at http://172.X.X.104:1400/xml/device_description.xml
Device is running Linux UPnP/1.0 Sonos/50.1-65071 (ZPS12)
****************************************************************

^C
Discover mode halted...

upnp> msearch

Entering discovery mode for 'upnp:rootdevice', Ctl+C to stop...

****************************************************************
SSDP notification message from 172.X.X.106:1400
XML file is located at http://172.X.X.106:1400/xml/device_description.xml
Device is running Linux UPnP/1.0 Sonos/50.1-65071 (ZPS1)
****************************************************************

****************************************************************
SSDP notification message from 172.X.X.107:1400
XML file is located at http://172.X.X.107:1400/xml/group_description.xml
Device is running Linux UPnP/1.0 Sonos/50.1-65071 (ZPS1)
****************************************************************

^C
Discover mode halted...

upnp> msearch

Entering discovery mode for 'upnp:rootdevice', Ctl+C to stop...

^C
Discover mode halted...

upnp> host list

	[0] 172.X.X.105:1400
	[1] 172.X.X.104:1400
	[2] 172.X.X.106:1400
	[3] 172.X.X.107:1400

**Comment by pelaxa** [comment]
Updated my config and added searchTimeout: 180 and saw all the speakers respond but still not seeing them discovered in homebridge.  Anyway I can provide the IP of the speakers to skip discovery?

**Comment by ebaauw** [comment]
> searchTimeout: 180

Note that this will delay the startup of homebridge’s server by 3 minutes.  The zoneplayers won’t be visible in HomeKit until the server has started.

> saw all the speakers respond

Where? In the homebridge log?

> Anyway I can provide the IP of the speakers to skip discovery?

No.

**Comment by pelaxa** [comment]
No. I saw them respond to another UPnP discovery tool I used. Even with 3 min, they are not getting discovered by the plugin.

**Comment by ebaauw** [comment]
Can you please run `upnp -z`?  That command comes with homebridge-lib and uses the same UPnP discovery as homebridge-zp.

**Comment by pelaxa** [comment]
ok, I think I know why this is not working.  The packets I was seeing were not responses to discovery, but ssdp:alive messages that get sent out periodically by the devices.

Seems like Sonos controller sends two packets for discovery, one to ipv4mcast (230.255.255.250) and 1 to broadcast (255.255.255.255).  The repeater that I have in place is picking up the broadcast packets and relaying them on the other vlan, but not the ipv4mcast packets.  The upnp lib only sends to ipv4mcast and that is why it does not work for me right now.

BTW,  I did run upnp in both search mode (no results) and listening mode (it does pickup the ssdp:alive messages).

**Comment by ebaauw** [comment]
The alive messages are multicast; `upnp` doesn’t listen to broadcasts.  When searching, `upnp` sends a multicast search request, containing the response address.  The devices respond with unicast messages.  When running `upnp` in listening mode, it should see the search request.  Can you check that is does on the Sonos side of your bridge, when the search is initiated from the homebridge side?

**Comment by pelaxa** [comment]
The relay was in debug mode, so I could see when it forwarded packets.

Thank you for all your help herein for the great homebridge plugins.  This is not really a bug and I won't have time to spend on it for the next couple of weeks so don't want this lingering open.
