### ISSUE TITLE
Automatically adjust volume when group players

### ISSUE THREAD

**Issue by normanmaurer** [ebaauw/homebridge-zp#85]
I love your plugin and use it regularly to group my Sonos speakers and so enable airplay2 on all of them. I wonder if it would be possible to support adjusting the volume of the grouped speakers to the volume to the speaker that supports airplay2 when doing so.

**Comment by ebaauw** [comment]
I don’t think Sonos provides a single command for a zone player to join a group and adjust the volume to the group coordinator.  Does the Sonos app support this?

Technically homebridge-zp could send a second command to adjust the volume after joining.  I’m not sure that I want to implement this, though:
- I’m reluctant to add functionality that is not in the Sonos app;
- I don’t know a user would request a normal join vs a join with automatic volume adjust.  Whether you want volume adjustment is probably dependent on which zone is joining what coordinator and what source the coordinator is playing.

**Comment by normanmaurer** [comment]
@ebaauw you are right it does not provide such a feature... Don't worry it was just a suggestion I will just implement something like this myself :)
