### ISSUE TITLE
Platform ZP not found

### ISSUE THREAD

**Issue by BobbySlopeCH** [ebaauw/homebridge-zp#86]
![CC671947-A1ED-4680-B7BA-393B9CDD421E](https://user-images.githubusercontent.com/50763727/61577192-35991100-aae4-11e9-8db0-78e1fc7d830a.jpeg)

**Comment by ebaauw** [comment]
Did you install homebridge-lib?

**Comment by BobbySlopeCH** [comment]
I installed directly from config-ui-x search bar. Maybe there was no dependency for homebridge-lib?

**Comment by BobbySlopeCH** [comment]
Managed to work after installing homebridge-lib. May you can add that to install directly from ui-x when installing sonos-zp

**Comment by BobbySlopeCH** [comment]
And as you wrote in readme speaker serive
Dont work in home app. Maybe you can implement it now as this type https://developer.apple.com/documentation/homekit/hmservicetypespeaker?language=objc
