### ISSUE TITLE
Dependency mismatch?

### ISSUE THREAD

**Issue by onefish2** [ebaauw/homebridge-zp#87]
I am getting this error:

I upgraded to the latest version of homebridge-lib 4.3.0. Now I get this error when I issue the command - sudo npm ls -g --depth=0
npm ERR! peer dep missing: homebridge-lib@~4.2.7, required by homebridge-zp@0.4.3

**Comment by ebaauw** [comment]
Please re-install homebridge-lib, this should revert to v4.2.7.

If you also use homebridge-hue, homebridge-otgw, or homebridge-ws, please re-install these as well.

**Comment by onefish2** [comment]
That worked. Thanks!!
