### ISSUE TITLE
Volume Control doesn‘t work

### ISSUE THREAD

**Issue by ScharV** [ebaauw/homebridge-zp#89]
Hey @ebaauw thank you for your perfect work and this great plugin. Just updated to latest version early this morning and added TV Mode. It works great. But I‘ve got one Problem with the remote widget. Only Play/Pause works but no Volume control whether I set up my config to Speaker, Fan, Switch or Bulb.
Hope you can help to fix.
Best regards Marv

**Comment by ebaauw** [comment]
The remote widget uses the hardware volume buttons on your iPhone or iPad for volume control. When pressing these, you should see log messages like:
```
[7/24/2019, 2:55:22 PM] [Sonos] Living Room TV Speaker: Volume Selector: Down
```

If they're not registering, you might need to select a different "television" and re-select the one you want to control.  The widget might be a bit flaky at times.

**Comment by ScharV** [comment]
Tested it and works great Thanks —> closed
