### ISSUE TITLE
sonos zp not found after switched off/on

### ISSUE THREAD

**Issue by conradhagemans** [ebaauw/homebridge-zp#9]
I like this stable homebridge plug-in.
If I move a sonos from one room to an other room it will not be found till homebridge is restarted.
So if the power of a sonos player is interupted you have to restart homebridge.

Is there not a way that the plug-in can find them after the sonos play is powered on?

**Comment by ebaauw** [comment]
Thanks, @conradhagemans 

There is a way to discover new Sonos speakers (more than one, actually).  However, currently, homebridge-zp uses the pre-v2 homebridge model for static accessories.  This means that the platform plug-in notifies homebridge of the accessories at startup time only.  I need to change homebridge-zp to use dynamic accessories, to be able to expose a newly discovered accessory at runtime.  See issue #1.
I haven't fully tested this, put power cycling a Sonos speaker should be possible without restarting homebridge, provided the Sonos speaker keeps the same IP address.  It might take up to 30 minutes, however, for homebridge-zp to renew its subscription and receive events from the speaker.
