### ISSUE TITLE
New upgrade failed to install

### ISSUE THREAD

**Issue by gladiatormax** [ebaauw/homebridge-zp#91]
Hi there,

With this new update i am getting strage errors and cannot install.
So i uninstalled the lib and reinstalled the zp but this is the error,
everting worked fine before,

C:\WINDOWS\system32>npm -g i homebridge-lib homebridge-zp
C:\Users\Gladiator\AppData\Roaming\npm\json -> C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-lib\cli\json.js
C:\Users\Gladiator\AppData\Roaming\npm\hap -> C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-lib\cli\hap.js
C:\Users\Gladiator\AppData\Roaming\npm\upnp -> C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-lib\cli\upnp.js
npm ERR! path C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-zp\node_modules\.bin\hap
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-zp\node_modules\.bin\hap'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gladiator\AppData\Roaming\npm-cache\_logs\2019-07-25T16_47_07_156Z-debug.log

as you can see i am running homebridge on windows.

**Comment by ebaauw** [comment]
What happens if you uninstall both and then install **only** homebridge-zp?

**Comment by gladiatormax** [comment]
Hi,
Thx for the quick respons,
as you can see, the same error,

C:\WINDOWS\system32>npm -g un homebridge-lib
up to date in 0.031s

C:\WINDOWS\system32>npm -g un homebridge-zp
up to date in 0.03s

C:\WINDOWS\system32>npm -g i homebridge-lib homebridge-zp
C:\Users\Gladiator\AppData\Roaming\npm\hap -> C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-lib\cli\hap.js
C:\Users\Gladiator\AppData\Roaming\npm\json -> C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-lib\cli\json.js
C:\Users\Gladiator\AppData\Roaming\npm\upnp -> C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-lib\cli\upnp.js
npm ERR! path C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-zp\node_modules\.bin\hap
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Gladiator\AppData\Roaming\npm\node_modules\homebridge-zp\node_modules\.bin\hap'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gladiator\AppData\Roaming\npm-cache\_logs\2019-07-25T17_28_04_929Z-debug.log

**Comment by gladiatormax** [comment]
this is when i only install zp wiyhout the lib,
C:\WINDOWS\system32>npm i homebridge-zp
npm WARN rm not removing C:\WINDOWS\system32\node_modules\.bin\json.cmd as it wasn't installed by C:\WINDOWS\system32\node_modules\homebridge-zp
npm WARN rm not removing C:\WINDOWS\system32\node_modules\.bin\hap.cmd as it wasn't installed by C:\WINDOWS\system32\node_modules\homebridge-zp
npm WARN rm not removing C:\WINDOWS\system32\node_modules\.bin\upnp.cmd as it wasn't installed by C:\WINDOWS\system32\node_modules\homebridge-zp
npm WARN rm not removing C:\WINDOWS\system32\node_modules\.bin\json as it wasn't installed by C:\WINDOWS\system32\node_modules\homebridge-zp
npm WARN rm not removing C:\WINDOWS\system32\node_modules\.bin\hap as it wasn't installed by C:\WINDOWS\system32\node_modules\homebridge-zp
npm WARN rm not removing C:\WINDOWS\system32\node_modules\.bin\upnp as it wasn't installed by C:\WINDOWS\system32\node_modules\homebridge-zp
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! path C:\WINDOWS\system32\node_modules\homebridge-zp\node_modules\.bin\hap
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\WINDOWS\system32\node_modules\homebridge-zp\node_modules\.bin\hap'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gladiator\AppData\Roaming\npm-cache\_logs\2019-07-25T17_30_18_808Z-debug.log

**Comment by ebaauw** [comment]
Could you please check if you can install homebridge-zp@1.0.1?  Looks like the thing I tried in 1.0.2 for #90 breaks the windows install.

**Comment by gladiatormax** [comment]
even that is not working anymore? strange no.

C:\WINDOWS\system32>npm i homebridge-zp@1.0.1
npm WARN system32@1.0.0 No description
npm WARN system32@1.0.0 No repository field.

npm ERR! path C:\WINDOWS\system32\node_modules\homebridge-zp\node_modules\homebridge-lib\cli\hap.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\WINDOWS\system32\node_modules\homebridge-zp\node_modules\homebridge-lib\cli\hap.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gladiator\AppData\Roaming\npm-cache\_logs\2019-07-25T17_54_49_626Z-debug.log

**Comment by ebaauw** [comment]
Did you uninstall homebridge-lib and then install **only** homebridge-zp?

**Comment by ebaauw** [comment]
What version of `npm` are you on?

**Comment by ebaauw** [comment]
I did managed get the same error on Raspbian, see #90.  Not sure if it's the same issue on Window, though...

**Comment by gladiatormax** [comment]
npm@6.10.2

**Comment by ebaauw** [comment]
Just published v1.0.3 and unpublished v1.0.1 an v1.0.2

**Comment by gladiatormax** [comment]
It is indeed working now on a windows install!
Thhank you for the great work, and keep it up !
