### ISSUE TITLE
Airplay 2 Devices showing in Homekit

### ISSUE THREAD

**Issue by adavison007** [ebaauw/homebridge-zp#92]
So even with Do not show Airplay 2 devices checked, they appear in homekit? I have redone this several times and even deleted the accessory file, airplay 2 now appearing since update, didn't  prior?

**Comment by ebaauw** [comment]
What's you config.json?  Could you please list the output of `ph topology -v`?

My zone players are too old for Airplay, but I understand you need to enable it, probably in the Sonos app settings.  I needs to be enabled when homebridge-zp first runs (after deleting `~/.homebridge/accessories/cachedAccessories`) and creates the accessories.  See https://github.com/ebaauw/homebridge-zp/issues/88#issuecomment-514796176.

**Comment by adavison007** [comment]
@ebaauw Here is the current JSON, Also I did have exclude checked prior to the first restart. I have also cleared the Accessory cache and they still remain... again this did work fine prior to the latest update I did yesterday.

I tried running ph topology -v in the command line and got nothing?

        {
            "name": "Sonos",
            "alarms": true,
            "excludeAirPlay": true,
            "nameScheme": "% Speakers",
            "service": "switch",
            "platform": "ZP"
        }

**Comment by ebaauw** [comment]
It must be the heat, I meant `zpinfo -H xx.xx.xx.xx topology -v`, where the xx’s are the ip address of one of your zone players.

Homebridge-zp lists the zones (rooms) and zone players it has discovered during startup, incl. the detected capabilities per zone player.  Like whether it supports Airplay.  Is that reported correctly?

> again this did work fine prior to the latest update I did yesterday.

Odd, I’ll double check the code what changes I made.

**Comment by adavison007** [comment]
> zpinfo -H xx.xx.xx.xx topology -v


[sonos.pdf](https://github.com/ebaauw/homebridge-zp/files/3436224/sonos.pdf)

**Comment by ebaauw** [comment]
Thanks.  So they're listen correctly, aren't they?

When you say it worked before the upgrade: was that a version <1.0.0?  It looks like the check for airPlay didn't make it through to the 1.0.0. code refactoring.  I'll add it.
 
Unrelated: the zone name for the zone with the Sub isn't yet handled correctly.  Could run `zpinfo -H 192.168.1.225 eventlog`.  This will subscribe to the Kitchen Beam and log all events it sends.  Just press ctrl-C to stop it.  I'm particularly interested in the ZoneGroupTopology event.

**Comment by adavison007** [comment]
> Thanks. So they're listen correctly, aren't they?
> 
> When you say it worked before the upgrade: was that a version <1.0.0? It looks like the check for airPlay didn't make it through to the 1.0.0. code refactoring. I'll add it.
> 
> Unrelated: the zone name for the zone with the Sub isn't yet handled correctly. Could run `zpinfo -H 192.168.1.225 eventlog`. This will subscribe to the Kitchen Beam and log all events it sends. Just press ctrl-C to stop it. I'm particularly interested in the ZoneGroupTopology event.

The previous version being the latest one prior to the errors from yesterdays update,e not sure which version, sorry.

here's the log...
[SUB.docx](https://github.com/ebaauw/homebridge-zp/files/3436338/SUB.docx)

**Comment by ebaauw** [comment]
Thanks.  So in a home theatre setup, the Sub is configured is a satellite, just like the surround speaker.  What does the Sonos app show as room name for the Kitchen in the EQ Settings?  Something like `Kitchen (+SW+LS+RS)`?

**Comment by adavison007** [comment]
> Thanks. So in a home theatre setup, the Sub is configured is a satellite, just like the surround speakers. What does the Sonos app show as room name for the Kitchen in the EQ Settings? Something like `Kitchen (+SW+LS+RS)`?

see attached  

![IMG_5495](https://user-images.githubusercontent.com/47482260/61967998-c2553a80-afce-11e9-8261-c5a0de71cc7f.png)

**Comment by ebaauw** [comment]
Seems like I lost the check for Airplay devices in v1.0.0 and later.  Will put it back in next version.
