### ISSUE TITLE
config.json: ignoring "brightness" for "service": "undefined"

### ISSUE THREAD

**Issue by daberlin** [ebaauw/homebridge-zp#98]
I get the following messages when home bridge starts up:

[2019-8-6 9:27:07 PM] [Sonos] Initializing ZP platform...
[2019-8-6 9:27:07 PM] [Sonos] homebridge-zp v1.0.8, node 10.16.1, homebridge v0.4.50, homebridge-lib v4.4.2
[2019-8-6 9:27:07 PM] [Sonos] warning: config.json: ignoring "brightness" for "service": "undefined"

My config:
        {
            "platform": "ZP",
            "name": "Sonos",
            "service": "switch",
            "brightness": true
        },

The warning seems superfluous...

**Comment by ebaauw** [comment]
It'a bug alright, but I'm afraid the warning might not be superfluous.  Is the volume exposed as `Brightness` or as `Volume`?

**Comment by daberlin** [comment]
Volume ("Lautstärke" in the Eve App)

**Comment by ebaauw** [comment]
And it should have been `Brightness` with this config.json setting.

**Comment by ebaauw** [comment]
Fixed in v1.0.9.

**Comment by daberlin** [comment]
Great - now it's brightness and the warning is gone.
Thanks a lot!
