### ISSUE TITLE
Last update caused too many issues and had to remove

### ISSUE THREAD

**Issue by adavison007** [ebaauw/homebridge-zp#99]
Love this plugin in, and appreciate your work.

Some constructive feedback... this plugin, since the last update, has effected other plugins from working, it also does not ignore Airplay 2 speakers and after a few days stops functioning. when removing the plugin, including the homebridge-lib, and the config, the speakers remain in homekit! Also when deleting the accessories file, they remain, had to rebuild hoobs home bridge completely.

I'd love to use this again, and appreciate your personal efforts in building it, so happy to test when you feel the above is resolved?

**Comment by ebaauw** [comment]
> since the last update

v1.0.8?

> has effected other plugins from working

That's not good.  I do need some more info to understand what's going on: what plugins stop working, what are the symptoms, what's in the homebridge log.

>  it also does not ignore Airplay 2 speakers

I don't have any zone players supporting Airplay myself so I cannot test this.  Double-checking the code, I think this should work.  Again, I would need to see the homebride log file (preferably `homebridge -D`) to understand what's going on.

> when removing the plugin, including the homebridge-lib, and the config, the speakers remain in homekit! 

That's considered a feature of dynamic platform accessories.  You can clean them starting `homebridge -R`, see https://github.com/nfarina/homebridge/pull/2190.

> Also when deleting the accessories file, they remain

Note that the TV accessories (like all standalone or non-bridged accessories) are neither persisted nor restored.  After removing homebridge-zp, their respective HAP servers are no longer started, but HomeKit keeps the accessory as unreachable.  You need to remove (unpair) them from HomeKit manually (just as you needed to pair them manually).

For the bridged accessories: this is technically not possible.  Are you sure you deleted the right file?  Normally `~/.homebridge/accessories/cachedAccessories`, but hoobs might have placed it at a different location.

**Comment by ebaauw** [comment]
> it also does not ignore Airplay 2 speakers

Got myself an IKEA SYMFONISK with AirPlay (see #101), so I can test the Airplay stuff.  I made a typo alright - will be fixed in the next version.

**Comment by adavison007** [comment]
> > it also does not ignore Airplay 2 speakers
> 
> Got myself an IKEA SYMFONISK with AirPlay (see #101), so I can test the Airplay stuff. I made a typo alright - will be fixed in the next version.

@ebaauw Thanks for the update, appreciate the support, how's the sound out of the Ikea Sonos? I'll happily reinstall and test the app when you let me know it's ready.

**Comment by ebaauw** [comment]
v1.0.9 should honour the `excludeAirPlay` setting.  It should also delete stale accessories.

For the other issues, I really need log files to understand what's going on.

> How's the sound out of the Ikea Sonos?

The reviews suggest it's a bit less than the Sonos Play:1 or Sonos One, but I find it very reasonable (given the price).  I wouldn't place a single bookshelf in a larger room, but they would do fine in a smaller home office, kitchen or kids bedroom.

I see another use case as well: I'm currently using an old Sonos Connect without any connected loudspeakers as designated coordinator.  As I move through my house, the zone players in the rooms join and leave the Connect.  Usually the Connect plays my favourite Internet radio station, but I've got an Apple AirPort Express (the 2012 model that now supports AirPlay 2) connected to the Line In.  This way I can AirPlay to my older Sonos players.  I suppose a bookshelf would provide the combined functionality (with the volume limit set to 1%) at a fourth of the cost of a new Connect and less than half the cost of a Sonos One.

**Comment by adavison007** [comment]
@ebaauw many thanks for this, I’ll try the plug-in in the next day or so and give feedback, happy to share logs, but will need some guidance on how.

Re the Sonos idea for airplay2 I like that, I have 10 connect amps (10 years old) and can’t afford to change them just for airplay 2 ... I tried airport express but found the functionality a bit clunky, especially turning on with Alexa and changing volume then turning off or changing volume with airplay 2 with express... Apple needs to make airplay 2 more like tv in HomeKit... seems silly the music plays from your phone rather than direct from Apple Music to Sonos (like google home and Alexa do).

Would like to discuss more with you on this later?

**Comment by adavison007** [comment]
@ebaauw Ok, installed, so far, so good, will keep you posted... I can confirm it did not add the airplay 2 speakers :)
